# /etc/nginx/secubox.d/haproxy.conf
# Installed by secubox-haproxy package
location /api/v1/haproxy/ {
    proxy_pass http://unix:/run/secubox/haproxy.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}
