server {
    include snippets/secubox-errorpages.conf;
    listen 9080;
    server_name git.gk2.secubox.in;
    root /srv/metablogizer/sites/git;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}
