server {
    include snippets/secubox-errorpages.conf;
    listen 0.0.0.0:8900;
    server_name lldh.ganimed.fr;
    root /srv/metablogizer/sites/lldh;
    index index.html index.htm;
    location ^~ /.well-known/acme-challenge/ { root /var/www/html; default_type text/plain; }
    location / { try_files $uri $uri/ /index.html; }
    access_log /var/log/nginx/lldh.ganimed.fr_access.log;
    access_log /var/log/nginx/secubox-hosts.log sbx_host;
}
