server {
    include snippets/secubox-errorpages.conf;
    listen 9080;
    server_name dork.gk2.secubox.in;
    root /srv/metablogizer/sites/meta-dork-aggregator;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
