# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
# Source-Disclosed License — All rights reserved except as expressly granted.
# See LICENCE-CMSD-1.0.md for terms.

server {
    include snippets/secubox-errorpages.conf;
    listen 0.0.0.0:8900;
    server_name wall.ganimed.fr;
    root /srv/metablogizer/sites/wall;
    index index.html index.htm;
    location ^~ /.well-known/acme-challenge/ { root /var/www/html; default_type text/plain; }
    location / { try_files $uri $uri/ /index.html; }
    access_log /var/log/nginx/wall.ganimed.fr_access.log;
    access_log /var/log/nginx/secubox-hosts.log sbx_host;
}
