# /etc/nginx/secubox.d/ksm.conf
# Installed by secubox-ksm package
location /api/v1/ksm/ {
    proxy_pass http://unix:/run/secubox/ksm.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}

location /ksm/ {
    alias /usr/share/secubox/www/ksm/;
    index index.html;
    try_files $uri $uri/ /ksm/index.html;
}
