# /etc/nginx/secubox.d/dns-provider.conf
# Installed by secubox-dns-provider package
location /api/v1/dns-provider/ {
    proxy_pass http://unix:/run/secubox/dns-provider.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}
