# /etc/nginx/secubox.d/admin.conf
# Installed by secubox-admin package
location /api/v1/admin/ {
    proxy_pass http://unix:/run/secubox/admin.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}

location /admin/ {
    alias /usr/share/secubox/www/admin/;
    index index.html;
    try_files $uri $uri/ /admin/index.html;
}
