# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# /run/secubox porte le bit collant et reste 1777 root:root (cf. #471) :
# on ne cree QUE le sous-arbre du module, jamais le parent.
d /var/lib/secubox/signal             0700 secubox-signal secubox-signal -
d /var/lib/secubox/signal/cli         0700 secubox-signal secubox-signal -
d /var/lib/secubox/signal/attachments 0700 secubox-signal secubox-signal -
d /var/log/secubox/signal             0750 secubox-signal secubox-signal -
