// SecuBox Companion — popup logic (P1)
const api = globalThis.browser ?? globalThis.chrome;

const DEFAULTS = {
  hubBase: "",                          // e.g. "https://admin.gk2.secubox.in"
  // Modules to probe (name shown + URL slug). Operator can edit in options.
  modules: ["hub", "crowdsec", "waf", "wireguard", "peertube", "photoprism", "nextcloud"],
  // PeerTube cookie-intake endpoint (backend lands with #401 P1.5 / #388).
  cookieEndpoint: "/api/v1/peertube/import/cookies",
  // SecuBox login endpoint (secubox-core JWT; any module's /auth/login works).
  loginEndpoint: "/api/v1/peertube/auth/login",
};

async function getConfig() {
  const stored = await api.storage.local.get(DEFAULTS);
  return { ...DEFAULTS, ...stored };
}

async function getToken() {
  return (await api.storage.local.get({ token: "" })).token;
}

async function authHeaders() {
  const t = await getToken();
  return t ? { Authorization: "Bearer " + t } : {};
}

async function login(cfg, username, password) {
  const r = await fetch(`${cfg.hubBase}${cfg.loginEndpoint}`, {
    method: "POST", credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ username, password }),
  });
  if (!r.ok) throw new Error("login failed (" + r.status + ")");
  const d = await r.json();
  if (!d.access_token) throw new Error("no token in response");
  await api.storage.local.set({ token: d.access_token });
  return d.access_token;
}

function setDot(el, state) {
  el.className = "dot dot-" + (state === "up" ? "up" : state === "down" ? "down" : "unknown");
}

async function probe(base, mod) {
  try {
    const r = await fetch(`${base}/api/v1/${mod}/health`, {
      credentials: "include", cache: "no-store", signal: AbortSignal.timeout(4000),
    });
    return r.ok ? "up" : "down";
  } catch {
    return "down";
  }
}

async function renderModules(cfg) {
  const list = document.getElementById("module-list");
  list.innerHTML = "";
  let up = 0, total = 0;
  for (const mod of cfg.modules) {
    total++;
    const li = document.createElement("li");
    const dot = document.createElement("span");
    setDot(dot, "unknown");
    const a = document.createElement("a");
    a.textContent = mod;
    a.href = `${cfg.hubBase}/${mod}/`;
    a.target = "_blank";
    li.append(dot, a);
    list.append(li);
    probe(cfg.hubBase, mod).then((s) => {
      setDot(dot, s);
      if (s === "up") { up++; }
      const o = document.getElementById("overall");
      setDot(o, up === total ? "up" : up === 0 ? "down" : "unknown");
    });
  }
}

function toNetscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by SecuBox Companion"];
  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : c.domain;
    const subdomFlag = c.domain.startsWith(".") ? "TRUE" : "FALSE";
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = Math.floor(c.expirationDate || 0);
    lines.push([domain, subdomFlag, path, secure, expiry, c.name, c.value].join("\t"));
  }
  return lines.join("\n") + "\n";
}

async function relayCookies(cfg) {
  const status = document.getElementById("relay-status");
  const loginBox = document.getElementById("login-box");
  if (!cfg.hubBase) { status.textContent = "Configure the hub first."; return; }
  status.textContent = "Reading YouTube cookies…";
  try {
    const cookies = await api.cookies.getAll({ domain: "youtube.com" });
    if (!cookies.length) {
      status.textContent = "No youtube.com cookies — log into YouTube in this browser first.";
      return;
    }
    const body = toNetscape(cookies);
    status.textContent = `Sending ${cookies.length} cookies…`;
    const r = await fetch(`${cfg.hubBase}${cfg.cookieEndpoint}`, {
      method: "POST", credentials: "include",
      headers: { "Content-Type": "text/plain", ...(await authHeaders()) }, body,
    });
    if (r.status === 401 || r.status === 403) {
      status.textContent = "SecuBox login required:";
      loginBox.classList.remove("hidden");
      return;
    }
    loginBox.classList.add("hidden");
    status.textContent = r.ok
      ? `Sent ${cookies.length} cookies — PeerTube is restarting; retry the import shortly.`
      : `Backend returned ${r.status}.`;
  } catch (e) {
    status.textContent = "Relay failed: " + (e?.message || e);
  }
}

document.addEventListener("DOMContentLoaded", async () => {
  const cfg = await getConfig();
  const openOpts = () => api.runtime.openOptionsPage();
  document.getElementById("open-options").addEventListener("click", openOpts);
  document.getElementById("open-options-footer").addEventListener("click", openOpts);
  document.getElementById("refresh").addEventListener("click", () => renderModules(cfg));
  document.getElementById("relay-cookies").addEventListener("click", () => relayCookies(cfg));
  document.getElementById("login-btn").addEventListener("click", async () => {
    const status = document.getElementById("relay-status");
    const u = document.getElementById("login-user").value.trim();
    const p = document.getElementById("login-pass").value;
    if (!u || !p) { status.textContent = "Enter SecuBox username + password."; return; }
    status.textContent = "Logging in…";
    try {
      await login(cfg, u, p);
      document.getElementById("login-pass").value = "";
      await relayCookies(cfg);   // retry now that we have a token
    } catch (e) {
      status.textContent = "Login failed: " + (e?.message || e);
    }
  });

  const hub = document.getElementById("open-hub");
  hub.href = cfg.hubBase || "#";

  if (!cfg.hubBase) {
    document.getElementById("needs-config").classList.remove("hidden");
    document.getElementById("module-list").innerHTML = '<li class="muted">Set the hub URL in settings.</li>';
    return;
  }
  renderModules(cfg);
});
