// SecuBox Companion — popup logic (P1)
const api = globalThis.browser ?? globalThis.chrome;

const DEFAULTS = {
  hubBase: "",                          // e.g. "https://admin.gk2.secubox.in"
  // Modules to probe (name shown + URL slug). Operator can edit in options.
  modules: ["hub", "crowdsec", "waf", "wireguard", "peertube", "photoprism", "nextcloud"],
  // Avatar credential-broker poke endpoint (#402): one place to share browser
  // auth with any backend service. youtube → PeerTube.
  cookieEndpoint: "/api/v1/avatar/cred/poke/youtube",
  // SecuBox login endpoint (secubox-core JWT; any module's /auth/login works).
  loginEndpoint: "/api/v1/peertube/auth/login",
  // Session-vault allowlist (#409): which domains to back up. Cookie access for
  // these needs matching host_permissions in the manifest.
  vaultDomains: ["youtube.com", "linkedin.com", "facebook.com"],
};

async function getConfig() {
  const stored = await api.storage.local.get(DEFAULTS);
  return { ...DEFAULTS, ...stored };
}

async function getToken() {
  return (await api.storage.local.get({ token: "" })).token;
}

async function authHeaders() {
  const t = await getToken();
  return t ? { Authorization: "Bearer " + t } : {};
}

async function login(cfg, username, password) {
  const r = await fetch(`${cfg.hubBase}${cfg.loginEndpoint}`, {
    method: "POST", credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ username, password }),
  });
  if (!r.ok) throw new Error("login failed (" + r.status + ")");
  const d = await r.json();
  if (!d.access_token) throw new Error("no token in response");
  await api.storage.local.set({ token: d.access_token });
  return d.access_token;
}

function setDot(el, state) {
  el.className = "dot dot-" + (state === "up" ? "up" : state === "down" ? "down" : "unknown");
}

async function probe(base, mod) {
  try {
    const r = await fetch(`${base}/api/v1/${mod}/health`, {
      credentials: "include", cache: "no-store", signal: AbortSignal.timeout(4000),
    });
    return r.ok ? "up" : "down";
  } catch {
    return "down";
  }
}

async function loadMetrics(cfg) {
  const set = (id, val, hot) => {
    const el = document.getElementById(id);
    if (!el) return;
    el.textContent = val;
    el.classList.toggle("m-hot", !!hot);
  };
  if (!cfg.hubBase) return;
  try {
    const r = await fetch(`${cfg.hubBase}/api/v1/system/metrics`, {
      credentials: "include", cache: "no-store",
      headers: { ...(await authHeaders()) }, signal: AbortSignal.timeout(5000),
    });
    if (!r.ok) return;
    const m = await r.json();
    const cpu = Math.round(m.cpu_percent ?? 0);
    const mem = Math.round(m.mem_percent ?? m.memory_percent ?? 0);
    const disk = Math.round(m.disk_percent ?? 0);
    const temp = m.cpu_temp != null ? Math.round(m.cpu_temp) : null;
    set("m-cpu", cpu + "%", cpu >= 90);
    set("m-mem", mem + "%", mem >= 90);
    set("m-disk", disk + "%", disk >= 90);
    set("m-temp", temp != null ? temp + "°" : "–", temp != null && temp >= 75);
  } catch { /* leave dashes */ }
}

async function renderModules(cfg) {
  const list = document.getElementById("module-list");
  list.innerHTML = "";
  let up = 0, total = 0;
  for (const mod of cfg.modules) {
    total++;
    const li = document.createElement("li");
    const dot = document.createElement("span");
    setDot(dot, "unknown");
    const a = document.createElement("a");
    a.textContent = mod;
    a.href = `${cfg.hubBase}/${mod}/`;
    a.target = "_blank";
    li.append(dot, a);
    list.append(li);
    probe(cfg.hubBase, mod).then((s) => {
      setDot(dot, s);
      if (s === "up") { up++; }
      const o = document.getElementById("overall");
      setDot(o, up === total ? "up" : up === 0 ? "down" : "unknown");
    });
  }
}

function toNetscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by SecuBox Companion"];
  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : c.domain;
    const subdomFlag = c.domain.startsWith(".") ? "TRUE" : "FALSE";
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = Math.floor(c.expirationDate || 0);
    lines.push([domain, subdomFlag, path, secure, expiry, c.name, c.value].join("\t"));
  }
  return lines.join("\n") + "\n";
}

// Robust JSON: never throws on HTML/empty bodies (the source of the
// "JSON.parse: unexpected character at line 1 column 1" errors).
async function safeJson(resp) {
  const text = await resp.text();
  if (!text) return {};
  try { return JSON.parse(text); }
  catch { return { _nonjson: text.slice(0, 120) }; }
}

// "Conformiser": the browser is the real cookie authority. Peek the avatar
// credential registry, then for EACH registered service relay the browser's
// live cookies (+ YouTube PO token if captured). One accessor, many logins.
async function syncAllLogins(cfg) {
  const status = document.getElementById("relay-status");
  const list = document.getElementById("cred-list");
  const loginBox = document.getElementById("login-box");
  list.innerHTML = "";
  if (!cfg.hubBase) { status.textContent = "Configure the hub first."; return; }
  status.textContent = "Discovering services…";

  let services;
  try {
    const r = await fetch(`${cfg.hubBase}/api/v1/avatar/cred/peek`, {
      credentials: "include", headers: { ...(await authHeaders()) },
    });
    if (r.status === 401 || r.status === 403) {
      status.textContent = "SecuBox login required:"; loginBox.classList.remove("hidden"); return;
    }
    if (!r.ok) { status.textContent = `Service discovery failed (HTTP ${r.status})`; return; }
    services = (await safeJson(r)).services || [];
  } catch (e) {
    status.textContent = "Discovery failed: " + (e?.message || e); return;
  }
  loginBox.classList.add("hidden");
  if (!services.length) { status.textContent = "No credential services registered on the hub."; return; }

  let ok = 0;
  for (const svc of services) {
    const li = document.createElement("li");
    list.append(li);
    try {
      const cookies = await api.cookies.getAll({ domain: svc.cookie_domain });
      if (!cookies.length) { li.textContent = `${svc.service}: not logged into ${svc.cookie_domain}`; continue; }
      const payload = { cookies: toNetscape(cookies) };
      if (svc.service === "youtube") {
        const s = await api.storage.local.get({ yt_po_token: "", yt_visitor_data: "" });
        if (s.yt_po_token) payload.po_token = s.yt_po_token;
        if (s.yt_visitor_data) payload.visitor_data = s.yt_visitor_data;
      }
      const pr = await fetch(`${cfg.hubBase}/api/v1/avatar/cred/poke/${svc.service}`, {
        method: "POST", credentials: "include",
        headers: { "Content-Type": "application/json", ...(await authHeaders()) },
        body: JSON.stringify(payload),
      });
      if (pr.status === 401 || pr.status === 403) { li.textContent = `${svc.service}: auth required`; loginBox.classList.remove("hidden"); continue; }
      const jr = await safeJson(pr);
      if (pr.ok && jr.success) { li.textContent = `${svc.service}: ✓ ${cookies.length} cookies relayed`; ok++; }
      else { li.textContent = `${svc.service}: ⚠ ${JSON.stringify(jr.results || jr._nonjson || pr.status)}`; }
    } catch (e) {
      li.textContent = `${svc.service}: ✗ ${e?.message || e}`;
    }
  }
  status.textContent = `Synced ${ok}/${services.length} login(s) from this browser.`;
}

// ── Session vault (#409): encrypted backup + profile restore ────────────────
async function loadVault(cfg) {
  const list = document.getElementById("vault-list");
  if (!list || !cfg.hubBase) return;
  list.innerHTML = "";
  try {
    const data = await Vault.list(cfg.hubBase, await authHeaders());
    const backups = data.backups || [];
    if (!backups.length) { list.innerHTML = '<li class="muted">No backups yet</li>'; return; }
    for (const b of backups) {
      const li = document.createElement("li");
      const span = document.createElement("span");
      span.style.flex = "1";
      const when = b.saved_at ? new Date(b.saved_at).toLocaleDateString() : "";
      span.textContent = `${b.profile}/${b.domain} (${(b.meta || {}).cookie_count || "?"}c, ${when})`;
      const rb = document.createElement("button");
      rb.className = "btn"; rb.textContent = "Restore"; rb.style.width = "auto"; rb.style.padding = "2px 8px";
      rb.addEventListener("click", () => doVaultRestore(cfg, b.profile, b.domain));
      li.append(span, rb);
      list.append(li);
    }
  } catch (e) {
    list.innerHTML = `<li class="muted">vault: ${e?.message || e}</li>`;
  }
}

async function doVaultBackup(cfg) {
  const status = document.getElementById("vault-status");
  const pass = document.getElementById("vault-pass").value;
  const profile = (document.getElementById("vault-profile").value || "default").trim();
  if (!cfg.hubBase) { status.textContent = "Configure the hub first."; return; }
  if (!pass) { status.textContent = "Enter a vault passphrase."; return; }
  status.textContent = "Encrypting + backing up…";
  try {
    const n = await Vault.backup(cfg.hubBase, await authHeaders(), pass, profile, cfg.vaultDomains);
    status.textContent = n ? `Backed up ${n} domain(s) (encrypted).` : "Nothing to back up (not logged into those sites?).";
    loadVault(cfg);
  } catch (e) { status.textContent = "Backup failed: " + (e?.message || e); }
}

async function doVaultRestore(cfg, profile, domain) {
  const status = document.getElementById("vault-status");
  const pass = document.getElementById("vault-pass").value;
  if (!pass) { status.textContent = "Enter the vault passphrase to restore."; return; }
  status.textContent = `Restoring ${domain}…`;
  try {
    const n = await Vault.restore(cfg.hubBase, await authHeaders(), pass, profile, domain);
    status.textContent = `Restored ${n} cookies for ${domain} — reload that site's tab.`;
  } catch (e) { status.textContent = "Restore failed (wrong passphrase?): " + (e?.message || e); }
}

document.addEventListener("DOMContentLoaded", async () => {
  const cfg = await getConfig();
  const openOpts = () => api.runtime.openOptionsPage();
  document.getElementById("open-options").addEventListener("click", openOpts);
  document.getElementById("open-options-footer").addEventListener("click", openOpts);
  document.getElementById("refresh").addEventListener("click", () => { renderModules(cfg); loadMetrics(cfg); });
  document.getElementById("relay-cookies").addEventListener("click", () => syncAllLogins(cfg));
  document.getElementById("login-btn").addEventListener("click", async () => {
    const status = document.getElementById("relay-status");
    const u = document.getElementById("login-user").value.trim();
    const p = document.getElementById("login-pass").value;
    if (!u || !p) { status.textContent = "Enter SecuBox username + password."; return; }
    status.textContent = "Logging in…";
    try {
      await login(cfg, u, p);
      document.getElementById("login-pass").value = "";
      await syncAllLogins(cfg);   // retry now that we have a token
    } catch (e) {
      status.textContent = "Login failed: " + (e?.message || e);
    }
  });

  const hub = document.getElementById("open-hub");
  hub.href = cfg.hubBase || "#";

  if (!cfg.hubBase) {
    document.getElementById("needs-config").classList.remove("hidden");
    document.getElementById("module-list").innerHTML = '<li class="muted">Set the hub URL in settings.</li>';
    return;
  }
  document.getElementById("vault-backup").addEventListener("click", () => doVaultBackup(cfg));
  renderModules(cfg);
  loadMetrics(cfg);
  loadVault(cfg);
});
