# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# SecuBox :: SOCKS local pour les clients LAN / wg-toolbox (PAC .onion -> Tor).
# JAMAIS ouvert : le SocksPort est lié à l'IP LAN (pas wildcard), et la
# SocksPolicy ferme tout sauf LAN + wg. L'ordre compte : Tor applique la
# PREMIERE policy qui matche, donc `reject *` reste en dernier.
SocksPort 192.168.1.200:9050
SocksPolicy accept 192.168.0.0/16
SocksPolicy accept 10.99.0.0/16
SocksPolicy reject *
