# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# SOCKS LAN pour clients LAN / wg-toolbox (PAC .onion -> Tor).
# L'option globale casserait le SocksPort mesh (secubox-macro).
# Confinement = bind IP LAN + nft. Pas d'options de policy.
SocksPort __LAN_IP__:9050
