# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# SOCKS LAN pour clients LAN / wg-toolbox (PAC .onion -> Tor).
# PAS de SocksPolicy ici : cette option est GLOBALE dans Tor et casserait le
# SocksPort mesh (secubox-macro). Confinement = bind sur l'IP LAN + nft.
SocksPort __LAN_IP__:9050
