# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Egress transparent .onion : DNSPort automap + TransPort. Posé par torctl
# UNIQUEMENT si aucun TransPort/DNSPort n'est déjà déclaré (coordination avec
# torrc-toolbox-egress.conf du toolbox — mêmes ports, une seule déclaration).
TransPort 127.0.0.1:9040
DNSPort 127.0.0.1:9053
AutomapHostsOnResolve 1
VirtualAddrNetworkIPv4 10.192.0.0/10
