# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
# Source-Disclosed License — All rights reserved except as expressly granted.
# See LICENCE-CMSD-1.0.md for terms.

"""
SecuBox-Deb :: profiles — génération des snippets nginx @waker (réveil-sur-accès)
CyberMind — https://cybermind.fr

Un vhost sleepable routé (portal_domain) reçoit un error_page 502/504 -> @waker
(le waker sert le splash + tire le réveil). always-on/manual/sans-portal : rien
(un 502 reste un 502). Écrit atomiquement, purge les snippets orphelins.
"""
from __future__ import annotations

import os
import tempfile
from pathlib import Path

from .lifecycle import effective_lifecycle
from .manifest import Manifest

_SNIPPET = """# generated by secubox-wakectl nginx-sync — do not edit
error_page 502 504 = @waker;
location @waker {{
    internal;
    proxy_pass http://unix:{sock}:/_wake/{domain};
    proxy_set_header Host $host;
}}
"""


def render_snippet(m: Manifest, *, waker_sock: str = "/run/secubox/waker.sock") -> str | None:
    """Snippet nginx pour `m`, ou None si `m` n'est pas un vhost sleepable routé
    (portal_domain absent, ou effective_lifecycle hors eager/on-demand)."""
    if m.portal_domain is None or effective_lifecycle(m) not in ("eager", "on-demand"):
        return None
    return _SNIPPET.format(sock=waker_sock, domain=m.portal_domain)


def _write_atomic(path: Path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise


def sync_snippets(*, manifests: dict[str, Manifest], out_dir: Path,
                  waker_sock: str = "/run/secubox/waker.sock") -> list[str]:
    """Écrit `<domain>.waker.conf` pour chaque module sleepable routé, purge les
    `*.waker.conf` orphelins (dont le domaine ne correspond plus à aucun module
    voulu — jamais les autres fichiers du répertoire), retourne les domaines
    écrits triés."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    want: dict[str, str] = {}
    for m in manifests.values():
        snip = render_snippet(m, waker_sock=waker_sock)
        if snip is not None and m.portal_domain is not None:
            want[m.portal_domain] = snip
    for dom, snip in want.items():
        _write_atomic(out_dir / f"{dom}.waker.conf", snip)
    for p in out_dir.glob("*.waker.conf"):
        if p.name[: -len(".waker.conf")] not in want:
            p.unlink()
    return sorted(want)
