# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
# Cree ici plutot que par le demon : le repertoire existe avec les bons droits
# meme si le service n'a jamais demarre.
d /var/lib/secubox/metanews 0750 secubox-metanews secubox -
d /var/cache/secubox/metanews 0750 secubox-metanews secubox -
