#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
# Source-Disclosed License — All rights reserved except as expressly granted.
# See LICENCE-CMSD-1.0.md for terms.

# SecuBox-Deb :: mail :: LXC lifecycle helpers (unprivileged veth on br-lxc).
# Sourced library — do not execute directly.

# Returns 0 if a container's rootfs exists under $LXC_BASE.
lxc_exists() {
    local name="$1"
    [ -d "${LXC_BASE:-/var/lib/lxc}/$name/rootfs" ]
}

# Returns 0 if a container is currently running.
lxc_running() {
    local name="$1"
    lxc-info -n "$name" 2>/dev/null | grep -q "State:.*RUNNING"
}

# Render lxc.config for the named container at the given IP.
# Args: name, ipv4 (e.g. "10.100.0.10" or "10.100.0.10/24"),
#       bridge (default "br-lxc"), gateway (default "10.100.0.1").
# Writes "$LXC_BASE/$name/config".
lxc_create_config() {
    local name="$1"
    local ip="$2"
    local bridge="${3:-br-lxc}"
    local gw="${4:-10.100.0.1}"
    local base="${LXC_BASE:-/var/lib/lxc}"
    local data="${DATA_PATH:-/data/volumes/mail}"
    local ip_cidr
    case "$ip" in
        */*) ip_cidr="$ip" ;;
        *)   ip_cidr="$ip/24" ;;
    esac
    mkdir -p "$base/$name"
    cat > "$base/$name/config" <<EOF
# Generated by mailctl — do not edit by hand
lxc.include = /usr/share/lxc/config/debian.common.conf

lxc.arch = linux64
lxc.uts.name = $name
lxc.rootfs.path = dir:$base/$name/rootfs

lxc.net.0.type = veth
lxc.net.0.link = $bridge
lxc.net.0.flags = up
lxc.net.0.ipv4.address = $ip_cidr
lxc.net.0.ipv4.gateway = $gw
lxc.net.0.name = eth0

lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536

# Bind mounts for persistent data
lxc.mount.entry = $data/vmail  var/vmail        none bind,create=dir 0 0
lxc.mount.entry = $data/config etc/mail-config  none bind,create=dir 0 0
lxc.mount.entry = $data/ssl    etc/ssl/mail     none bind,create=dir 0 0

lxc.cgroup2.memory.max = 1G
lxc.start.auto = 1
EOF
}

# Start a container and wait until it reports RUNNING (max 10s).
lxc_start_safely() {
    local name="$1"
    lxc-start -n "$name" -d
    local i
    for i in 1 2 3 4 5 6 7 8 9 10; do
        lxc_running "$name" && return 0
        sleep 1
    done
    return 1
}

# Run a command inside a container; propagate exit status.
lxc_attach_run() {
    local name="$1"; shift
    lxc-attach -n "$name" -- "$@"
}
