# /etc/nginx/secubox.d/webmail-lxc.conf
# Installed by secubox-webmail-lxc package
location /api/v1/webmail-lxc/ {
    proxy_pass http://unix:/run/secubox/webmail-lxc.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}
