# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
"""Cross-engine SOCIAL parity harness — Python side (#662).

Loads the SAME ``social-cookie-id-fixtures.json`` the Go core uses
(``../secubox-toolbox-ng/testdata``) and asserts ``social.cookie_id_hash``
reproduces each fixture's ``expect``.

Python is the source of truth: the ``expect`` values were GENERATED by this very
``social.cookie_id_hash``. The Go side (cmd/sbxmitm/social_test.go) must
reproduce them byte-for-byte. Both files reading identical inputs is what makes
the parity meaningful — the same anti-rig discipline as the jar parity harness.
"""
from __future__ import annotations

import json
import os

from secubox_toolbox import social

_HERE = os.path.dirname(os.path.abspath(__file__))
# tests/ → packages/secubox-toolbox → packages → packages/secubox-toolbox-ng
_NG_TESTDATA = os.path.normpath(
    os.path.join(_HERE, "..", "..", "secubox-toolbox-ng", "testdata"))
_FIXTURES = os.path.join(_NG_TESTDATA, "social-cookie-id-fixtures.json")


def _load():
    with open(_FIXTURES, encoding="utf-8") as f:
        return json.load(f)


def test_cookie_id_hash_parity():
    data = _load()
    assert data["fixtures"], "no fixtures"
    failures = []
    for fx in data["fixtures"]:
        got = social.cookie_id_hash(
            fx["tracker_domain"], fx["cookie_name"], fx["cookie_value"])
        if got != fx["expect"]:
            failures.append((fx, got))
    assert not failures, f"cookie_id_hash drift: {failures}"


def test_cookie_id_hash_invariants():
    # domain + name are lower-cased; the value is NOT.
    assert social.cookie_id_hash("A.NET", "N", "v") == social.cookie_id_hash("a.net", "n", "v")
    assert social.cookie_id_hash("a.net", "n", "V") != social.cookie_id_hash("a.net", "n", "v")
