# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
"""Cross-engine mac_hash (WG persona identity) parity harness — Python side
(#662 Phase 6 prep).

Loads the SAME ``machash-fixtures.json`` + ``wg-peers-fixture.json`` the Go core
uses (``../secubox-toolbox-ng/testdata``), points ``_common._WG_PEERS_DB`` at the
fixture WG DB (NOT the real ``/var/lib/secubox/toolbox/wg-peers.json``), resets
the WG cache, and asserts ``_common.mac_hash_of`` == each fixture's ``expected``.

Python is the source of truth: the ``expected`` values were GENERATED by
``sha256(pubkey.encode()).hexdigest()[:16]`` (the very algorithm
``_common._wg_hash_of`` runs). The Go side (machash_test.go) must reproduce them
byte-for-byte. Both files reading identical inputs is what makes the parity
meaningful (and non-circular).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from mitmproxy_addons import _common

_HERE = os.path.dirname(os.path.abspath(__file__))
# tests/ → packages/secubox-toolbox → packages → packages/secubox-toolbox-ng
_NG_TESTDATA = os.path.normpath(
    os.path.join(_HERE, "..", "..", "secubox-toolbox-ng", "testdata"))
_FIXTURES = os.path.join(_NG_TESTDATA, "machash-fixtures.json")


def _load():
    with open(_FIXTURES, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture
def wg_env(monkeypatch):
    """Point _common at the fixture WG DB and reset the mtime cache so the
    override is (re)read. Mirrors exactly the (path, cache, mtime) surface the
    Go wgHashOf reads (wgPeersPath + resetWGCache)."""
    data = _load()
    wg_path = os.path.join(_NG_TESTDATA, data["wg_peers_file"].replace("/", os.sep))
    monkeypatch.setattr(_common, "_WG_PEERS_DB", Path(wg_path))
    monkeypatch.setattr(_common, "_WG_PEERS_MTIME", 0.0)
    _common._WG_PEERS_CACHE.clear()
    return data


def test_machash_parity(wg_env):
    failures = []
    for fx in wg_env["fixtures"]:
        # _common returns None where Go returns ""; normalise None → "".
        got = _common.mac_hash_of(fx["ip"]) or ""
        if got != fx["expected"]:
            failures.append(
                f"mac_hash_of({fx['ip']!r})={got!r} want {fx['expected']!r}"
                f"  ({fx.get('why')})")
    assert not failures, "Python↔fixture mac_hash parity mismatches:\n" + "\n".join(failures)


def test_machash_coverage(wg_env):
    # The fixtures must exercise the discriminating cases, else parity is vacuous.
    resolved = subnet_miss = off_subnet = empty = False
    for fx in wg_env["fixtures"]:
        ip, exp = fx["ip"], fx["expected"]
        if ip == "":
            empty = True
        elif exp != "":
            resolved = True
        elif ip.startswith("10.99.1."):
            subnet_miss = True
        else:
            off_subnet = True
    assert resolved and subnet_miss and off_subnet and empty, (
        f"coverage incomplete: resolved={resolved} subnet_miss={subnet_miss} "
        f"off_subnet={off_subnet} empty={empty}")


def test_machash_missing_db_fail_open(wg_env):
    # A missing WG DB fails open to None (best-effort), never raises.
    _common._WG_PEERS_DB = Path("/nonexistent/secubox/wg-peers.json")
    _common._WG_PEERS_MTIME = 0.0
    _common._WG_PEERS_CACHE.clear()
    assert _common.mac_hash_of("10.99.1.10") is None
