# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
"""Cross-engine JAR parity harness — Python side (#662 Phase 4).

Loads the SAME ``jar-fixtures.json`` + fixed test key the Go core uses
(``../secubox-toolbox-ng/testdata``), points ``privacy.JAR_KEY_PATH`` at the
test key (NOT the real ``/etc/secubox/secrets/privacy-jar.key``), resets the
jar-key cache, and asserts ``privacy.fake_id`` == each fixture's ``expect``.

Python is the source of truth: the ``expect`` values were GENERATED by this
very ``privacy.fake_id`` with the test key. The Go side (jar_test.go) must
reproduce them byte-for-byte. Both files reading identical inputs is what makes
the parity meaningful.
"""
from __future__ import annotations

import json
import os

import pytest

from secubox_toolbox import privacy

_HERE = os.path.dirname(os.path.abspath(__file__))
# tests/ → packages/secubox-toolbox → packages → packages/secubox-toolbox-ng
_NG_TESTDATA = os.path.normpath(
    os.path.join(_HERE, "..", "..", "secubox-toolbox-ng", "testdata"))
_FIXTURES = os.path.join(_NG_TESTDATA, "jar-fixtures.json")


def _load():
    with open(_FIXTURES, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture
def jar_env(monkeypatch):
    """Point privacy at the test key file and reset the cache so the override
    is (re)read. Mirrors exactly the (path, cache) surface the Go loadJarKey
    reads."""
    data = _load()
    key_path = os.path.join(_NG_TESTDATA, data["key_file"].replace("/", os.sep))
    monkeypatch.setattr(privacy, "JAR_KEY_PATH", key_path)
    monkeypatch.setattr(privacy, "_jar_key_cache", {"v": None})
    return data


def test_jar_key_loads_canonical(jar_env):
    # _jar_key() must strip the file's surrounding whitespace back to the
    # canonical key declared in key_hex (proves .strip() parity with TrimSpace).
    key = privacy._jar_key()
    assert key is not None
    assert key.hex() == jar_env["key_hex"]


def test_jar_parity(jar_env):
    failures = []
    for fx in jar_env["fixtures"]:
        got = privacy.fake_id(fx["client"], fx["tracker"], fx["cookie_name"])
        if got != fx["expect"]:
            failures.append(
                f"fake_id({fx['client']!r},{fx['tracker']!r},{fx['cookie_name']!r})"
                f"={got!r} want {fx['expect']!r}  ({fx.get('why')})")
    assert not failures, "Python↔fixture jar parity mismatches:\n" + "\n".join(failures)


def test_jar_shapes_covered(jar_env):
    # Every _shape branch must appear, else parity is vacuous for that branch.
    shapes = set()
    for fx in jar_env["fixtures"]:
        e = fx["expect"]
        if e.startswith("GA1."):
            shapes.add("ga")
        elif e.startswith("fb."):
            shapes.add("fb")
        elif len(e) == 36 and e[8] == "-":
            shapes.add("uuid")
        elif len(e) == 32:
            shapes.add("hex")
    assert shapes == {"ga", "fb", "uuid", "hex"}, shapes


def test_jar_folding(jar_env):
    # Two subdomains of the same registrable tracker fold to the SAME fake id.
    a = privacy.fake_id("foldclient", "px.doubleclick.net", "uid")
    b = privacy.fake_id("foldclient", "ads.doubleclick.net", "uid")
    assert a is not None and a == b


def test_jar_none_cases(jar_env):
    # fake_id returns None exactly where Go fakeID returns ("", False).
    assert privacy.fake_id("", "t.example", "uid") is None       # empty client
    assert privacy.fake_id("c", "", "uid") is None                # empty tracker
    # empty key → None
    monkeypatched_empty = {"v": b""}
    object.__setattr__(privacy, "_jar_key_cache", monkeypatched_empty)
    assert privacy.fake_id("c", "t.example", "uid") is None
