# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
# Source-Disclosed License — All rights reserved except as expressly granted.
# See LICENCE-CMSD-1.0.md for terms.
# SecuBox (#1819) : le proxy d'égress n'a de sens qu'une fois la boîte à outils
# provisionnée (CA de l'inspection). Sans elle, il bouclait au redémarrage
# (60 000+ essais sur gk3) faute du certificat qu'il copie au départ.
[Unit]
ConditionPathExists=/etc/secubox/toolbox/ca-wg/sbxmitm-ca-cert.pem
