// cmd/secubox/internal/manifest/makefile.go
package manifest

import (
	"fmt"
	"strings"
)

// GenerateMakefile creates a Makefile from a manifest
func GenerateMakefile(m *Manifest) string {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf(`# Auto-generated by secubox gen v%s
# Run: make image

MANIFEST := manifest.yaml
VERSION := %s
BOARD := %s
ARCH := %s
IMAGE_NAME := secubox-$(BOARD)-$(VERSION)

.PHONY: all image rootfs partition boot compress checksums clean

all: image

image: rootfs partition boot compress checksums
	@echo "Build complete: $(IMAGE_NAME).img.gz"

rootfs:
	@echo "=== Building rootfs ==="
	secubox build --stage rootfs --manifest $(MANIFEST)

partition:
	@echo "=== Creating partitions ==="
	secubox build --stage partition --manifest $(MANIFEST)

boot:
	@echo "=== Installing bootloader ==="
	secubox build --stage boot --manifest $(MANIFEST)

compress:
	@echo "=== Compressing images ==="
`, m.SecuboxVersion, m.SecuboxVersion, m.Board, m.Arch))

	// Add compression commands based on output formats
	for _, format := range m.Output.Formats {
		switch format {
		case "img.gz":
			sb.WriteString("\tgzip -k $(IMAGE_NAME).img\n")
		case "img.xz":
			sb.WriteString("\txz -k $(IMAGE_NAME).img\n")
		}
	}

	// Checksums
	sb.WriteString(`
checksums:
	@echo "=== Generating checksums ==="
`)
	for _, sum := range m.Output.Checksums {
		sb.WriteString(fmt.Sprintf("\t%ssum $(IMAGE_NAME).img* > %sSUMS\n", sum, strings.ToUpper(sum)))
	}

	// Clean and additional targets
	sb.WriteString(`
clean:
	rm -rf rootfs/ *.img *.img.gz *.img.xz SHA*SUMS

# Platform-specific targets
.PHONY: vdi qcow2 iso

vdi: image
	qemu-img convert -f raw -O vdi $(IMAGE_NAME).img $(IMAGE_NAME).vdi

qcow2: image
	qemu-img convert -f raw -O qcow2 $(IMAGE_NAME).img $(IMAGE_NAME).qcow2

iso: rootfs
	secubox build --stage iso --manifest $(MANIFEST)
`)

	return sb.String()
}
