// cmd/secubox/internal/manifest/manifest.go
package manifest

import (
	"fmt"
	"time"

	"github.com/CyberMind-FR/secubox-deb/cmd/secubox/internal/profile"
	"gopkg.in/yaml.v3"
)

// Manifest represents the build manifest
type Manifest struct {
	SecuboxVersion string             `yaml:"secubox_version"`
	GeneratedAt    string             `yaml:"generated_at"`
	Board          string             `yaml:"board"`
	Tier           string             `yaml:"tier"`
	Arch           string             `yaml:"arch"`
	Packages       []string           `yaml:"packages"`
	Kernel         ManifestKernel     `yaml:"kernel"`
	Partitions     ManifestPartitions `yaml:"partitions"`
	Boot           ManifestBoot       `yaml:"boot"`
	Output         ManifestOutput     `yaml:"output"`
}

type ManifestKernel struct {
	Version string          `yaml:"version"`
	DTS     string          `yaml:"dts,omitempty"`
	Modules ManifestModules `yaml:"modules"`
}

// ManifestModules defines kernel modules to enable or blacklist
type ManifestModules struct {
	Enable    []string `yaml:"enable"`
	Blacklist []string `yaml:"blacklist"`
}

type ManifestPartitions struct {
	ESP  string `yaml:"esp"`
	Root string `yaml:"root"`
	Data string `yaml:"data"`
}

type ManifestBoot struct {
	Method      string `yaml:"method"`
	KernelImage string `yaml:"kernel_image,omitempty"`
}

type ManifestOutput struct {
	Formats   []string `yaml:"formats"`
	Checksums []string `yaml:"checksums"`
}

// Generate creates a manifest from profile and board
func Generate(p *profile.Profile, b *profile.Board, version string) *Manifest {
	m := &Manifest{
		SecuboxVersion: version,
		GeneratedAt:    time.Now().UTC().Format(time.RFC3339),
		Board:          b.Name,
		Tier:           p.Name,
		Arch:           b.Arch,
		Packages:       p.Packages.Required,
		Kernel: ManifestKernel{
			Version: p.Kernel.Version,
			DTS:     b.Boot.DTS,
			Modules: ManifestModules{
				Enable:    p.Kernel.Modules.Enable,
				Blacklist: p.Kernel.Modules.Blacklist,
			},
		},
		// TODO: Read partition sizes from board config (board/*/config.mk)
		// Currently hardcoded; see issue tracking board-specific partitions
		Partitions: ManifestPartitions{
			ESP:  "256M",
			Root: "6G",
			Data: "2G",
		},
		Boot: ManifestBoot{
			Method:      b.Boot.Method,
			KernelImage: b.Boot.KernelImage,
		},
		Output: ManifestOutput{
			Formats:   []string{"img.gz", "img.xz"},
			Checksums: []string{"sha256", "sha512"},
		},
	}

	return m
}

// ToYAML serializes the manifest to YAML
func (m *Manifest) ToYAML() ([]byte, error) {
	header := "# Auto-generated by secubox gen v" + m.SecuboxVersion + "\n"
	header += "# Date: " + m.GeneratedAt + "\n"
	header += "# Do not edit manually - regenerate with: secubox gen\n\n"

	data, err := yaml.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("marshal manifest: %w", err)
	}

	return append([]byte(header), data...), nil
}
