// cmd/secubox/internal/manifest/manifest_test.go
package manifest

import (
	"strings"
	"testing"

	"github.com/CyberMind-FR/secubox-deb/cmd/secubox/internal/profile"
)

func TestGenerate(t *testing.T) {
	p := &profile.Profile{
		Name: "test",
		Packages: profile.Packages{
			Required: []string{"secubox-core", "secubox-hub"},
		},
		Kernel: profile.Kernel{
			Version: "6.6",
		},
	}

	b := &profile.Board{
		Name: "mochabin",
		Arch: "arm64",
		Boot: profile.Boot{
			Method:      "uboot",
			KernelImage: "Image",
			DTS:         "armada-7040-mochabin",
		},
	}

	m := Generate(p, b, "2.8.0")

	if m.SecuboxVersion != "2.8.0" {
		t.Errorf("SecuboxVersion = %q, want %q", m.SecuboxVersion, "2.8.0")
	}
	if m.Board != "mochabin" {
		t.Errorf("Board = %q, want %q", m.Board, "mochabin")
	}
	if len(m.Packages) != 2 {
		t.Errorf("Packages = %d, want 2", len(m.Packages))
	}

	// Additional coverage for Kernel, Tier, Arch, Boot, Output
	if m.Kernel.Version != "6.6" {
		t.Errorf("Kernel.Version = %q, want %q", m.Kernel.Version, "6.6")
	}
	if m.Tier != "test" {
		t.Errorf("Tier = %q, want %q", m.Tier, "test")
	}
	if m.Arch != "arm64" {
		t.Errorf("Arch = %q, want %q", m.Arch, "arm64")
	}
	if m.Boot.Method != "uboot" {
		t.Errorf("Boot.Method = %q, want %q", m.Boot.Method, "uboot")
	}
	if m.Boot.KernelImage != "Image" {
		t.Errorf("Boot.KernelImage = %q, want %q", m.Boot.KernelImage, "Image")
	}
	if len(m.Output.Formats) != 2 {
		t.Errorf("Output.Formats count = %d, want 2", len(m.Output.Formats))
	}
	if len(m.Output.Checksums) != 2 {
		t.Errorf("Output.Checksums count = %d, want 2", len(m.Output.Checksums))
	}
}

func TestToYAML(t *testing.T) {
	p := &profile.Profile{
		Name: "test",
		Packages: profile.Packages{
			Required: []string{"secubox-core"},
		},
		Kernel: profile.Kernel{
			Version: "6.6",
		},
	}

	b := &profile.Board{
		Name: "mochabin",
		Arch: "arm64",
		Boot: profile.Boot{
			Method: "uboot",
		},
	}

	m := Generate(p, b, "2.8.0")
	yaml, err := m.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML() error = %v", err)
	}

	// Check header
	if !strings.Contains(string(yaml), "# Auto-generated by secubox gen") {
		t.Error("YAML missing header comment")
	}

	// Check content (YAML doesn't quote simple strings)
	if !strings.Contains(string(yaml), "secubox_version: 2.8.0") {
		t.Error("YAML missing secubox_version")
	}
	if !strings.Contains(string(yaml), "board: mochabin") {
		t.Error("YAML missing board")
	}
}

func TestToYAML_EmptyManifest(t *testing.T) {
	// Test that ToYAML handles an empty/minimal manifest without error
	m := &Manifest{
		SecuboxVersion: "1.0.0",
		GeneratedAt:    "2025-01-01T00:00:00Z",
	}

	yaml, err := m.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML() on empty manifest error = %v", err)
	}

	// Should still have header
	if !strings.Contains(string(yaml), "# Auto-generated by secubox gen v1.0.0") {
		t.Error("YAML missing header comment for empty manifest")
	}

	// Should contain the minimal fields
	if !strings.Contains(string(yaml), "secubox_version: 1.0.0") {
		t.Error("YAML missing secubox_version for empty manifest")
	}
}

func TestGenerateMakefile(t *testing.T) {
	m := &Manifest{
		SecuboxVersion: "2.8.0",
		Board:          "mochabin",
		Arch:           "arm64",
		Output: ManifestOutput{
			Formats:   []string{"img.gz", "img.xz"},
			Checksums: []string{"sha256", "sha512"},
		},
	}

	makefile := GenerateMakefile(m)

	if !strings.Contains(makefile, "VERSION := 2.8.0") {
		t.Error("Makefile missing VERSION")
	}
	if !strings.Contains(makefile, "BOARD := mochabin") {
		t.Error("Makefile missing BOARD")
	}
	if !strings.Contains(makefile, "ARCH := arm64") {
		t.Error("Makefile missing ARCH")
	}
	if !strings.Contains(makefile, "image:") {
		t.Error("Makefile missing image target")
	}
	if !strings.Contains(makefile, "gzip -k") {
		t.Error("Makefile missing gzip command")
	}
	if !strings.Contains(makefile, "xz -k") {
		t.Error("Makefile missing xz command")
	}
	if !strings.Contains(makefile, "sha256sum") {
		t.Error("Makefile missing sha256sum")
	}
	if !strings.Contains(makefile, "sha512sum") {
		t.Error("Makefile missing sha512sum")
	}
	if !strings.Contains(makefile, "qemu-img convert") {
		t.Error("Makefile missing qemu-img targets")
	}
}
