# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>

"""mitmproxy addon :: detect cert-pinning failures and auto-whitelist.

Phase 6.N (#496) — when an SNI generates repeated TLS handshake failures
because the client rejects our mitm cert (= cert pinning), append the
SNI to a DYNAMIC whitelist file. A systemd path watcher then restarts
mitm-wg, picking up the new ignore_hosts regex on next start.

Why : manually maintaining a static bypass list is futile — every app
update brings new pinned subdomains (people-pa, playatoms-pa, quake-pa,
oauthaccountmanager, securitydomain-pa, ...). Auto-learning closes the
loop : the first user to hit a pinned host pays a 3-failure tax, then
every subsequent user passes through opaque.

Storage : /var/lib/secubox/toolbox/mitm-bypass-dynamic.conf
Format  : same as static (one regex per line, # comments).

The static file (`mitm-bypass.conf`) stays the source of truth for known
pinned hosts (Signal, banks, etc.). The dynamic file accumulates learned
ones, with a marker comment saying when each was added.

Threshold defaults : 3 fails within 5 minutes → add. Tunable via env.
"""
from __future__ import annotations

import os
import re
import time
from collections import defaultdict, deque
from pathlib import Path

from mitmproxy import ctx, tls

DYNAMIC_FILE = Path("/var/lib/secubox/toolbox/mitm-bypass-dynamic.conf")
THRESHOLD = int(os.environ.get("SECUBOX_PIN_THRESHOLD", "3"))
WINDOW_SECONDS = int(os.environ.get("SECUBOX_PIN_WINDOW", "300"))

# Whitelist of hostnames that should NEVER be auto-added (own infra, etc.)
NEVER_AUTO = re.compile(
    r"^(127\.0\.0\.1|10\.|172\.|192\.168\.|"
    r"(.+\.)?(secubox|gk2|cybermind|maegia)\.\w+)$",
    re.IGNORECASE,
)

# Don't bother for obvious junk
_VALID_SNI = re.compile(r"^[a-z0-9.-]+\.[a-z]{2,}$", re.IGNORECASE)


class CertPinDetect:
    def __init__(self):
        # per-SNI : deque of failure timestamps (auto-evict older than window)
        self._fails: dict[str, deque] = defaultdict(deque)
        # Already-added hosts so we don't re-append (load existing on startup)
        self._already_added: set[str] = set()
        self._load_existing()

    def _load_existing(self):
        try:
            if DYNAMIC_FILE.exists():
                for line in DYNAMIC_FILE.read_text().splitlines():
                    line = line.strip()
                    if line and not line.startswith("#"):
                        # Strip the regex wrapper `(.+\.)?` to recover the bare host
                        m = re.match(r"^\(\.\+\\\.\)\?(.+)\\?\.com|", line)
                        # Just record the line as-is, we use it for dedupe via the line itself
                        self._already_added.add(line)
        except Exception as e:
            ctx.log.warn(f"[cert-pin] could not load dynamic file: {e}")

    def _normalize_to_pattern(self, sni: str) -> str:
        """Turn 'people-pa.googleapis.com' → '(.+\\.)?googleapis\\.com'.
        Strip the first label so a single entry covers all subdomains."""
        parts = sni.split(".")
        if len(parts) < 2:
            return None
        # Drop the leftmost label (subdomain), match the rest of the domain
        # e.g. people-pa.googleapis.com → covers *.googleapis.com
        # e.g. tg.socdm.com → covers *.socdm.com
        # e.g. www.foo.bar.com → covers *.bar.com (last 2 labels)
        domain = ".".join(parts[-2:]).replace(".", r"\.")
        return r"(.+\.)?" + domain

    def _should_consider(self, sni: str) -> bool:
        if not sni or not _VALID_SNI.match(sni):
            return False
        if NEVER_AUTO.match(sni):
            return False
        return True

    def _maybe_add(self, sni: str) -> None:
        now = time.time()
        q = self._fails[sni]
        q.append(now)
        # Evict old
        while q and (now - q[0]) > WINDOW_SECONDS:
            q.popleft()
        if len(q) < THRESHOLD:
            return
        # Threshold crossed → write pattern to dynamic file
        pattern = self._normalize_to_pattern(sni)
        if not pattern or pattern in self._already_added:
            return
        try:
            DYNAMIC_FILE.parent.mkdir(parents=True, exist_ok=True)
            with DYNAMIC_FILE.open("a") as f:
                if not self._already_added:
                    f.write("# auto-generated by cert_pin_detect — Phase 6.N (#496)\n")
                    f.write("# learned from repeated TLS handshake failures (cert pinning detected)\n")
                f.write(f"{pattern}    # {sni} learned {int(now)}\n")
            self._already_added.add(pattern)
            ctx.log.warn(f"[cert-pin] LEARNED pinned host : {sni} → {pattern} (after {THRESHOLD} fails)")
            # Reset counter so we don't re-trigger immediately
            q.clear()
        except Exception as e:
            ctx.log.warn(f"[cert-pin] write failed for {sni}: {e}")

    # ── mitmproxy hooks ──

    def tls_failed_clienthello(self, data) -> None:
        """Client rejected our cert → cert pinning detected."""
        try:
            sni = getattr(data.client_hello, "sni", None) if hasattr(data, "client_hello") else None
            if self._should_consider(sni):
                self._maybe_add(sni)
        except Exception as e:
            ctx.log.debug(f"[cert-pin] hook err: {e}")


addons = [CertPinDetect()]
