# /etc/nginx/secubox.d/glances.conf
# Installed by secubox-glances package
location /api/v1/glances/ {
    proxy_pass http://unix:/run/secubox/glances.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}

location /glances/ {
    alias /usr/share/secubox/www/glances/;
    index index.html;
    try_files $uri $uri/ /glances/index.html;
}
