"""
SecuBox-Deb :: secubox-rtty
CyberMind — https://cybermind.fr
Author: Gerald Kerma <gandalf@gk2.net>
License: Proprietary / ANSSI CSPN candidate

Remote terminal access module using rtty (web-based terminal).
"""
from fastapi import FastAPI, APIRouter, Depends, HTTPException
from pydantic import BaseModel
from secubox_core.auth import router as auth_router, require_jwt
from secubox_core.logger import get_logger
import subprocess
import json
import secrets
import time
from pathlib import Path
from typing import Optional, List

app = FastAPI(
    title="secubox-rtty",
    version="1.0.0",
    root_path="/api/v1/rtty"
)
app.include_router(auth_router, prefix="/auth")
router = APIRouter()
log = get_logger("rtty")

# Paths
RTTY_CONF = Path("/etc/rtty/rtty.conf")
RTTY_TOKENS = Path("/var/lib/secubox/rtty/tokens.json")
RTTY_LOG = Path("/var/log/rtty/rtty.log")
CONFIG_CACHE = Path("/var/lib/secubox/rtty/config_cache.json")

# Default rtty config template
DEFAULT_CONFIG = """# SecuBox RTTY Configuration
# Generated by secubox-rtty

# Server settings
host = "0.0.0.0"
port = 5912
http_port = 5913

# SSL/TLS
ssl = false
ssl_cert = "/etc/ssl/certs/rtty.crt"
ssl_key = "/etc/ssl/private/rtty.key"

# Authentication
token = "CHANGE_ME_TOKEN"

# Interface
web_root = "/usr/share/rtty/www"

# Logging
log_level = "info"
"""


def _run_cmd(cmd: List[str], timeout: int = 30) -> dict:
    """Run a command and return result."""
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Command timed out"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def _service_status() -> dict:
    """Get rtty service status."""
    result = subprocess.run(
        ["systemctl", "is-active", "rtty"],
        capture_output=True,
        text=True
    )
    active = result.stdout.strip() == "active"

    enabled_result = subprocess.run(
        ["systemctl", "is-enabled", "rtty"],
        capture_output=True,
        text=True
    )
    enabled = enabled_result.stdout.strip() == "enabled"

    # Get process info if running
    pid = None
    uptime = None
    if active:
        pid_result = subprocess.run(
            ["pgrep", "-x", "rtty"],
            capture_output=True,
            text=True
        )
        if pid_result.returncode == 0:
            pid = int(pid_result.stdout.strip().split()[0])
            # Get uptime from /proc
            try:
                stat = Path(f"/proc/{pid}/stat").read_text()
                starttime = int(stat.split()[21])
                uptime_sec = int(Path("/proc/uptime").read_text().split()[0])
                boot_time = time.time() - uptime_sec
                start_time = boot_time + (starttime / 100)
                uptime = int(time.time() - start_time)
            except Exception:
                pass

    return {
        "active": active,
        "enabled": enabled,
        "pid": pid,
        "uptime_seconds": uptime
    }


def _get_config() -> dict:
    """Parse rtty.conf into dict."""
    config = {
        "host": "0.0.0.0",
        "port": 5912,
        "http_port": 5913,
        "ssl": False,
        "ssl_cert": "",
        "ssl_key": "",
        "token": "",
        "web_root": "/usr/share/rtty/www",
        "log_level": "info"
    }

    if RTTY_CONF.exists():
        for line in RTTY_CONF.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key in config:
                    # Type conversion
                    if isinstance(config[key], bool):
                        config[key] = value.lower() in ("true", "yes", "1")
                    elif isinstance(config[key], int):
                        try:
                            config[key] = int(value)
                        except ValueError:
                            pass
                    else:
                        config[key] = value
    return config


def _save_config(config: dict):
    """Save config dict to rtty.conf."""
    lines = [
        "# SecuBox RTTY Configuration",
        "# Generated by secubox-rtty",
        "",
        "# Server settings",
        f'host = "{config.get("host", "0.0.0.0")}"',
        f'port = {config.get("port", 5912)}',
        f'http_port = {config.get("http_port", 5913)}',
        "",
        "# SSL/TLS",
        f'ssl = {"true" if config.get("ssl") else "false"}',
        f'ssl_cert = "{config.get("ssl_cert", "")}"',
        f'ssl_key = "{config.get("ssl_key", "")}"',
        "",
        "# Authentication",
        f'token = "{config.get("token", "")}"',
        "",
        "# Interface",
        f'web_root = "{config.get("web_root", "/usr/share/rtty/www")}"',
        "",
        "# Logging",
        f'log_level = "{config.get("log_level", "info")}"',
    ]
    RTTY_CONF.parent.mkdir(parents=True, exist_ok=True)
    RTTY_CONF.write_text("\n".join(lines) + "\n")


def _get_tokens() -> List[dict]:
    """Get access tokens from tokens.json."""
    if RTTY_TOKENS.exists():
        try:
            return json.loads(RTTY_TOKENS.read_text())
        except Exception:
            pass
    return []


def _save_tokens(tokens: List[dict]):
    """Save access tokens to tokens.json."""
    RTTY_TOKENS.parent.mkdir(parents=True, exist_ok=True)
    RTTY_TOKENS.write_text(json.dumps(tokens, indent=2))


def _parse_sessions() -> List[dict]:
    """Parse active terminal sessions from rtty or connections."""
    sessions = []

    # Check for WebSocket connections to rtty port
    config = _get_config()
    http_port = config.get("http_port", 5913)

    result = subprocess.run(
        ["ss", "-tunp"],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        for line in result.stdout.splitlines():
            if f":{http_port}" in line or "rtty" in line:
                parts = line.split()
                if len(parts) >= 5:
                    local = parts[4] if len(parts) > 4 else "-"
                    remote = parts[5] if len(parts) > 5 else "-"

                    # Extract client IP
                    client_ip = "-"
                    client_port = "-"
                    if ":" in remote:
                        addr_parts = remote.rsplit(":", 1)
                        client_ip = addr_parts[0].strip("[]")
                        client_port = addr_parts[1] if len(addr_parts) > 1 else "-"

                    # Skip internal connections
                    if client_ip in ("127.0.0.1", "::1", "-"):
                        continue

                    sessions.append({
                        "client_ip": client_ip,
                        "client_port": client_port,
                        "protocol": parts[0],
                        "local_addr": local,
                        "state": parts[1] if len(parts) > 1 else "UNKNOWN"
                    })

    return sessions


# ══════════════════════════════════════════════════════════════════════════════
# API Endpoints
# ══════════════════════════════════════════════════════════════════════════════

@router.get("/health")
async def health():
    """Health check endpoint (public)."""
    return {"status": "ok", "module": "rtty", "version": "1.0.0"}


@router.get("/status")
async def status(user=Depends(require_jwt)):
    """Get rtty service status."""
    svc = _service_status()
    config = _get_config()
    sessions = _parse_sessions()

    return {
        "service": svc,
        "host": config.get("host", "0.0.0.0"),
        "port": config.get("port", 5912),
        "http_port": config.get("http_port", 5913),
        "ssl_enabled": config.get("ssl", False),
        "config_exists": RTTY_CONF.exists(),
        "active_sessions": len(sessions),
        "tokens_count": len(_get_tokens())
    }


@router.get("/sessions")
async def get_sessions(user=Depends(require_jwt)):
    """Get active terminal sessions."""
    sessions = _parse_sessions()
    return {"sessions": sessions, "count": len(sessions)}


@router.post("/start")
async def start(user=Depends(require_jwt)):
    """Start rtty service."""
    result = _run_cmd(["systemctl", "start", "rtty"])
    log.info("RTTY start requested: %s", result.get("success"))
    return result


@router.post("/stop")
async def stop(user=Depends(require_jwt)):
    """Stop rtty service."""
    result = _run_cmd(["systemctl", "stop", "rtty"])
    log.info("RTTY stop requested: %s", result.get("success"))
    return result


@router.post("/restart")
async def restart(user=Depends(require_jwt)):
    """Restart rtty service."""
    result = _run_cmd(["systemctl", "restart", "rtty"])
    log.info("RTTY restart requested: %s", result.get("success"))
    return result


@router.get("/config")
async def get_config(user=Depends(require_jwt)):
    """Get rtty configuration."""
    config = _get_config()
    # Mask token for security
    config_display = config.copy()
    if config_display.get("token"):
        config_display["token"] = "***" + config_display["token"][-4:] if len(config_display["token"]) > 4 else "****"

    return {
        "config": config_display,
        "config_exists": RTTY_CONF.exists()
    }


class ConfigUpdate(BaseModel):
    host: Optional[str] = None
    port: Optional[int] = None
    http_port: Optional[int] = None
    ssl: Optional[bool] = None
    ssl_cert: Optional[str] = None
    ssl_key: Optional[str] = None
    token: Optional[str] = None
    log_level: Optional[str] = None


@router.post("/config")
async def update_config(req: ConfigUpdate, user=Depends(require_jwt)):
    """Update rtty configuration."""
    try:
        # Backup current config
        if RTTY_CONF.exists():
            backup = RTTY_CONF.with_suffix(".conf.bak")
            backup.write_text(RTTY_CONF.read_text())

        # Get current config and update
        config = _get_config()
        update_data = req.model_dump(exclude_none=True)

        for key, value in update_data.items():
            config[key] = value

        _save_config(config)
        log.info("RTTY config updated")

        return {"success": True, "message": "Config updated. Restart service to apply."}
    except Exception as e:
        log.error("Config update failed: %s", e)
        return {"success": False, "error": str(e)}


@router.get("/logs")
async def get_logs(lines: int = 100, user=Depends(require_jwt)):
    """Get rtty service logs."""
    # Try rtty log file first
    if RTTY_LOG.exists():
        try:
            all_lines = RTTY_LOG.read_text().splitlines()
            return {"lines": all_lines[-lines:]}
        except Exception as e:
            log.warning("Failed to read rtty log: %s", e)

    # Fall back to journalctl
    result = subprocess.run(
        ["journalctl", "-u", "rtty", "-n", str(lines), "--no-pager"],
        capture_output=True,
        text=True,
        timeout=10
    )
    return {"lines": result.stdout.splitlines()}


class TokenRequest(BaseModel):
    name: str
    ttl: int = 86400  # 24 hours default


@router.post("/token")
async def generate_token(req: TokenRequest, user=Depends(require_jwt)):
    """Generate an access token for terminal session."""
    token = secrets.token_urlsafe(32)
    expires = int(time.time()) + req.ttl

    tokens = _get_tokens()

    # Add new token
    token_entry = {
        "name": req.name,
        "token": token,
        "created": int(time.time()),
        "expires": expires,
        "ttl": req.ttl
    }
    tokens.append(token_entry)

    # Clean expired tokens
    now = int(time.time())
    tokens = [t for t in tokens if t.get("expires", 0) > now]

    _save_tokens(tokens)
    log.info("Access token generated: %s", req.name)

    config = _get_config()

    return {
        "success": True,
        "token": token,
        "name": req.name,
        "expires": expires,
        "ttl": req.ttl,
        "access_url": f"http{'s' if config.get('ssl') else ''}://localhost:{config.get('http_port', 5913)}/?token={token}"
    }


@router.get("/tokens")
async def list_tokens(user=Depends(require_jwt)):
    """List all access tokens."""
    tokens = _get_tokens()
    now = int(time.time())

    # Don't expose actual tokens, just metadata
    return {
        "tokens": [
            {
                "name": t.get("name"),
                "created": t.get("created"),
                "expires": t.get("expires"),
                "expired": t.get("expires", 0) < now
            }
            for t in tokens
        ]
    }


@router.delete("/tokens/{name}")
async def revoke_token(name: str, user=Depends(require_jwt)):
    """Revoke an access token."""
    tokens = _get_tokens()
    new_tokens = [t for t in tokens if t.get("name") != name]

    if len(new_tokens) == len(tokens):
        return {"success": False, "error": "Token not found"}

    _save_tokens(new_tokens)
    log.info("Access token revoked: %s", name)
    return {"success": True, "message": f"Token {name} revoked"}


# Three-fold architecture endpoints

@router.get("/components")
async def components(user=Depends(require_jwt)):
    """List rtty components (Three-fold architecture)."""
    return {
        "components": [
            {
                "name": "rtty",
                "type": "service",
                "description": "Web-based terminal server daemon",
                "status": _service_status()["active"]
            },
            {
                "name": "rtty.conf",
                "type": "config",
                "description": "Main configuration file",
                "exists": RTTY_CONF.exists()
            },
            {
                "name": "tokens.json",
                "type": "data",
                "description": "Access tokens database",
                "exists": RTTY_TOKENS.exists()
            }
        ]
    }


@router.get("/access")
async def access(user=Depends(require_jwt)):
    """Get access endpoints (Three-fold architecture)."""
    config = _get_config()
    host = config.get("host", "localhost")
    port = config.get("port", 5912)
    http_port = config.get("http_port", 5913)
    ssl = config.get("ssl", False)
    protocol = "https" if ssl else "http"
    ws_protocol = "wss" if ssl else "ws"

    if host == "0.0.0.0":
        host = "localhost"

    return {
        "endpoints": [
            {
                "name": "Web Terminal",
                "protocol": protocol,
                "host": host,
                "port": http_port,
                "url": f"{protocol}://{host}:{http_port}/"
            },
            {
                "name": "WebSocket",
                "protocol": ws_protocol,
                "host": host,
                "port": http_port,
                "url": f"{ws_protocol}://{host}:{http_port}/ws"
            },
            {
                "name": "API",
                "protocol": protocol,
                "host": host,
                "port": port,
                "url": f"{protocol}://{host}:{port}/"
            }
        ]
    }


app.include_router(router)
