// SPDX-License-Identifier: LicenseRef-CMSD-1.0
// Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
//
// Cross-engine mac_hash (WG persona identity) parity harness — Go side
// (#662 Phase 6 prep).
//
// Loads testdata/machash-fixtures.json + the SAME testdata/wg-peers-fixture.json
// the Python side reads, points wgPeersPath at the fixture, and asserts
// macHashOf(ip) == each fixture's expected. The Python side
// (../secubox-toolbox/tests/test_machash_parity.py) monkeypatches
// _common._WG_PEERS_DB to the SAME fixture and drives _common.mac_hash_of; both
// must agree → the WG persona hash is byte-exact across engines. Python is the
// source of truth: the expected values were GENERATED by sha256(pubkey)[:16] in
// Python, never hand-computed in Go (non-circular parity).
package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type machashFixture struct {
	IP       string `json:"ip"`
	Expected string `json:"expected"`
	Why      string `json:"why"`
}

type machashFile struct {
	WGPeersFile string           `json:"wg_peers_file"`
	Fixtures    []machashFixture `json:"fixtures"`
}

func loadMachashFile(t *testing.T) (machashFile, string) {
	t.Helper()
	dir := testdataDir(t) // shared with policy_test.go (cmd/sbxmitm → ../../testdata)
	raw, err := os.ReadFile(filepath.Join(dir, "machash-fixtures.json"))
	if err != nil {
		t.Fatalf("read machash fixtures: %v", err)
	}
	var mf machashFile
	if err := json.Unmarshal(raw, &mf); err != nil {
		t.Fatalf("parse machash fixtures: %v", err)
	}
	if len(mf.Fixtures) == 0 {
		t.Fatal("no machash fixtures")
	}
	return mf, dir
}

// withWGFixture points wgPeersPath at the fixture and resets the cache so the
// override is (re)read, restoring the original path afterwards. Mirrors exactly
// the (path, cache) surface the Python _wg_hash_of reads.
func withWGFixture(t *testing.T, mf machashFile, dir string) {
	t.Helper()
	orig := wgPeersPath
	wgPeersPath = filepath.Join(dir, mf.WGPeersFile)
	resetWGCache()
	t.Cleanup(func() {
		wgPeersPath = orig
		resetWGCache()
	})
}

// TestMacHashParity: macHashOf == Python-generated expected for every fixture.
func TestMacHashParity(t *testing.T) {
	mf, dir := loadMachashFile(t)
	withWGFixture(t, mf, dir)
	for _, fx := range mf.Fixtures {
		got := macHashOf(fx.IP)
		if got != fx.Expected {
			t.Errorf("macHashOf(%q)=%q want %q  (%s)", fx.IP, got, fx.Expected, fx.Why)
		}
	}
}

// TestMacHashCoverage: the fixtures must exercise the discriminating cases, else
// "parity" is vacuous. We need at least one resolved WG peer (non-empty), one
// in-subnet miss (empty), one off-subnet IP (empty), and the empty ip (empty).
func TestMacHashCoverage(t *testing.T) {
	mf, dir := loadMachashFile(t)
	withWGFixture(t, mf, dir)
	var sawResolved, sawSubnetMiss, sawOffSubnet, sawEmpty bool
	for _, fx := range mf.Fixtures {
		switch {
		case fx.IP == "":
			sawEmpty = true
		case fx.Expected != "":
			sawResolved = true
		case len(fx.IP) >= 8 && fx.IP[:8] == "10.99.1.":
			sawSubnetMiss = true
		default:
			sawOffSubnet = true
		}
	}
	if !sawResolved || !sawSubnetMiss || !sawOffSubnet || !sawEmpty {
		t.Fatalf("machash coverage incomplete: resolved=%v subnetMiss=%v offSubnet=%v empty=%v",
			sawResolved, sawSubnetMiss, sawOffSubnet, sawEmpty)
	}
}

// TestWGCacheReload: wgHashOf reflects the file's content; after pointing at a
// missing path it fails open to "" (best-effort, never panics).
func TestWGCacheReload(t *testing.T) {
	mf, dir := loadMachashFile(t)
	withWGFixture(t, mf, dir)
	// A resolved peer from the fixture returns non-empty.
	if got := wgHashOf("10.99.1.10"); got == "" {
		t.Fatal("wgHashOf(10.99.1.10) empty — fixture not loaded")
	}
	// Repoint at a missing file → reload → fail-open to "".
	wgPeersPath = filepath.Join(dir, "does-not-exist.json")
	resetWGCache()
	if got := wgHashOf("10.99.1.10"); got != "" {
		t.Fatalf("wgHashOf with missing file = %q want \"\"", got)
	}
}
