// SPDX-License-Identifier: LicenseRef-CMSD-1.0
// Copyright (c) 2026 CyberMind — Gérald Kerma <devel@cybermind.fr>
//
// Cross-engine SOCIAL parity + decision harness — Go side (#662).
//
// Anti-rig: loads testdata/social-cookie-id-fixtures.json (GENERATED by the real
// secubox_toolbox.social.cookie_id_hash) and asserts cookieIDHash reproduces
// every `expect` byte-for-byte — Python is the source of truth, exactly like the
// jar parity harness. The Python side is tests/test_social_parity.py.
//
// The rest exercises the ported decision surface: deny-list, registrableSocial
// (the addon flavour, NOT policy.registrable), the 3rd-party Set-Cookie + Cookie
// edge extraction, consent_state classification, and the relay buffer/flush.
package main

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
)

type socialCookieFixture struct {
	TrackerDomain string `json:"tracker_domain"`
	CookieName    string `json:"cookie_name"`
	CookieValue   string `json:"cookie_value"`
	Expect        string `json:"expect"`
	Why           string `json:"why"`
}

type socialCookieFile struct {
	Fixtures []socialCookieFixture `json:"fixtures"`
}

// TestCookieIDHashParity: cookieIDHash == the Python-generated expect for every
// fixture. This is the anti-rig that proves the Go hash is byte-identical to
// social.cookie_id_hash (lower-case domain+name, raw value, NUL separators).
func TestCookieIDHashParity(t *testing.T) {
	dir := testdataDir(t)
	raw, err := os.ReadFile(filepath.Join(dir, "social-cookie-id-fixtures.json"))
	if err != nil {
		t.Fatalf("read social fixtures: %v", err)
	}
	var f socialCookieFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse social fixtures: %v", err)
	}
	if len(f.Fixtures) == 0 {
		t.Fatal("no social cookie-id fixtures")
	}
	for _, fx := range f.Fixtures {
		got := cookieIDHash(fx.TrackerDomain, fx.CookieName, fx.CookieValue)
		if got != fx.Expect {
			t.Errorf("cookieIDHash(%q,%q,%q)=%q want %q  (%s)",
				fx.TrackerDomain, fx.CookieName, fx.CookieValue, got, fx.Expect, fx.Why)
		}
	}
}

// TestCookieIDHashFolding: domain+name are lower-cased but the value is NOT —
// the explicit invariant the store contract pins.
func TestCookieIDHashFolding(t *testing.T) {
	if cookieIDHash("DoubleClick.NET", "IDE", "AbC") != cookieIDHash("doubleclick.net", "ide", "AbC") {
		t.Error("domain+name must be case-folded")
	}
	if cookieIDHash("d.net", "n", "AbC") == cookieIDHash("d.net", "n", "abc") {
		t.Error("value must NOT be case-folded")
	}
}

func TestIsDenyListed(t *testing.T) {
	deny := []string{"PHPSESSID", "session", " csrftoken ", "__cf_bm", "consent", "locale", "", "   "}
	for _, n := range deny {
		if !isDenyListed(n) {
			t.Errorf("isDenyListed(%q) = false, want true", n)
		}
	}
	allow := []string{"IDE", "_ga", "_fbp", "uid", "datr"}
	for _, n := range allow {
		if isDenyListed(n) {
			t.Errorf("isDenyListed(%q) = true, want false", n)
		}
	}
}

// TestRegistrableSocial: the addon flavour — IP literals pass through (NOT ""),
// no port strip semantics needed, the larger multi-label table.
func TestRegistrableSocial(t *testing.T) {
	cases := map[string]string{
		"www.lemonde.fr":        "lemonde.fr",
		"cdn.api.example.co.uk": "example.co.uk",
		"tracker.com":           "tracker.com",
		"a.b.c.doubleclick.net": "doubleclick.net",
		"WWW.Example.COM":       "example.com",
		"sub.example.com.au":    "example.com.au",
		"192.168.1.1":           "192.168.1.1", // IP literal as-is (addon), store drops later
		".trailing.dot.net.":    "dot.net",
		"single":                "single",
		"":                      "",
	}
	for in, want := range cases {
		if got := registrableSocial(in); got != want {
			t.Errorf("registrableSocial(%q)=%q want %q", in, got, want)
		}
	}
}

func TestParseSetCookieNameValue(t *testing.T) {
	cases := []struct {
		in          string
		name, value string
		ok          bool
	}{
		{"IDE=AHWqTUm; Domain=.doubleclick.net; Path=/", "IDE", "AHWqTUm", true},
		{"  _ga = GA1.2.3 ; Max-Age=63", "_ga", "GA1.2.3", true},
		{"Secure; HttpOnly", "", "", false},
		{"=novalue", "", "", false},
		{"empty=", "empty", "", true},
	}
	for _, c := range cases {
		n, v, ok := parseSetCookieNameValue(c.in)
		if n != c.name || v != c.value || ok != c.ok {
			t.Errorf("parseSetCookieNameValue(%q)=(%q,%q,%v) want (%q,%q,%v)", c.in, n, v, ok, c.name, c.value, c.ok)
		}
	}
}

func TestExtractSetCookieDomainAttr(t *testing.T) {
	cases := map[string]string{
		"IDE=x; Domain=.doubleclick.net; Path=/": "doubleclick.net",
		"a=b; domain=Example.COM":                "example.com",
		"a=b; Path=/":                            "",
		"a=b":                                    "",
		"a=domainlike=1; Path=/":                 "", // value containing "domain" is not the attr
	}
	for in, want := range cases {
		if got := extractSetCookieDomainAttr(in); got != want {
			t.Errorf("extractSetCookieDomainAttr(%q)=%q want %q", in, got, want)
		}
	}
}

func TestSrcSiteFromReferer(t *testing.T) {
	req := httptest.NewRequest("GET", "https://tracker.io/p.gif", nil)
	if got := srcSiteFromReferer(req); got != "" {
		t.Errorf("no referer → %q want \"\"", got)
	}
	req.Header.Set("Referer", "https://www.lemonde.fr/article?x=1")
	if got := srcSiteFromReferer(req); got != "lemonde.fr" {
		t.Errorf("referer → %q want lemonde.fr", got)
	}
	req.Header.Del("Referer")
	req.Header.Set("Origin", "https://news.example.co.uk")
	if got := srcSiteFromReferer(req); got != "example.co.uk" {
		t.Errorf("origin fallback → %q want example.co.uk", got)
	}
}

// helper: build a response with the given Set-Cookie lines.
func respWithSetCookies(lines ...string) *http.Response {
	h := http.Header{}
	for _, l := range lines {
		h.Add("Set-Cookie", l)
	}
	return &http.Response{Header: h}
}

// TestSocialEdgesThirdParty: a 3rd-party Set-Cookie (Domain= a different eTLD+1)
// on a 1st-party page yields one edge with the right src_site/tracker_domain.
func TestSocialEdgesThirdParty(t *testing.T) {
	req := httptest.NewRequest("GET", "https://ads.doubleclick.net/pixel", nil)
	resp := respWithSetCookies("IDE=AHWqTUm; Domain=.doubleclick.net; Path=/")
	// reqHost is the responding host (doubleclick) — but src_site is also derived
	// from it; so to model a TRUE 3rd-party we use the Domain attr differing from
	// the request host's registrable. Here both are doubleclick.net → 1st-party,
	// expect NO edge.
	edges := socialEdgesFor("machash1", req, resp, "ads.doubleclick.net", "https://ads.doubleclick.net/pixel", "", newConsentLog())
	if len(edges) != 0 {
		t.Fatalf("1st-party Set-Cookie should yield 0 edges, got %d", len(edges))
	}

	// Now a genuine 3rd-party: the page host is lemonde.fr, a Set-Cookie with
	// Domain=.doubleclick.net (the embedded tracker setting on its own domain via
	// the request being to doubleclick but src derived from referer is the
	// request-cookie path; the Set-Cookie path uses reqHost as src). Model the
	// addon's Set-Cookie path: reqHost=lemonde.fr, Domain attr=doubleclick.net.
	resp2 := respWithSetCookies("IDE=AHWqTUm; Domain=.doubleclick.net; Path=/")
	edges = socialEdgesFor("machash1", req, resp2, "www.lemonde.fr", "https://www.lemonde.fr/", "", newConsentLog())
	if len(edges) != 1 {
		t.Fatalf("3rd-party Set-Cookie should yield 1 edge, got %d", len(edges))
	}
	e := edges[0]
	if e.SrcSite != "lemonde.fr" || e.TrackerDomain != "doubleclick.net" {
		t.Errorf("edge src/tracker = %q/%q want lemonde.fr/doubleclick.net", e.SrcSite, e.TrackerDomain)
	}
	if e.CookieIDHashVal != cookieIDHash("doubleclick.net", "IDE", "AHWqTUm") {
		t.Errorf("edge cookie id hash mismatch: %q", e.CookieIDHashVal)
	}
	if e.ConsentState != "none_seen" {
		t.Errorf("consent_state = %q want none_seen", e.ConsentState)
	}
}

// TestSocialEdgesDenyAndIP: deny-listed names produce no edge; IP-literal hosts
// produce no edge (registrableSocial returns the IP, store drops it — but src
// derivation: an IP src_site == IP tracker → not 3rd party anyway).
func TestSocialEdgesDenyAndIP(t *testing.T) {
	req := httptest.NewRequest("GET", "https://x/", nil)
	resp := respWithSetCookies("PHPSESSID=abc; Domain=.doubleclick.net")
	edges := socialEdgesFor("m", req, resp, "www.lemonde.fr", "https://www.lemonde.fr/", "", newConsentLog())
	if len(edges) != 0 {
		t.Fatalf("deny-listed cookie should yield 0 edges, got %d", len(edges))
	}
	// empty mac hash → no edges (R3-only gate)
	if e := socialEdgesFor("", req, respWithSetCookies("IDE=x; Domain=.doubleclick.net"), "www.lemonde.fr", "u", "", newConsentLog()); len(e) != 0 {
		t.Fatalf("empty macHash should yield 0 edges, got %d", len(e))
	}
}

// TestSocialEdgesRequestCookiePath: a request TO a tracker carrying a Cookie,
// with a Referer to a different 1st-party, yields an edge attributed to the
// referer's site.
func TestSocialEdgesRequestCookiePath(t *testing.T) {
	req := httptest.NewRequest("GET", "https://ads.doubleclick.net/px", nil)
	req.Header.Set("Cookie", "IDE=AHWqTUm; session=secret")
	req.Header.Set("Referer", "https://www.lemonde.fr/article")
	// No Set-Cookie in the response; src_site = registrableSocial(reqHost) =
	// doubleclick.net; the Set-Cookie loop emits nothing; the request-Cookie tail
	// uses ctxSite=lemonde.fr (referer) != tracker doubleclick.net → edge. The
	// deny-listed `session` cookie is skipped, so exactly 1 edge (IDE).
	edges := socialEdgesFor("m", req, &http.Response{Header: http.Header{}}, "ads.doubleclick.net", "https://ads.doubleclick.net/px", "", newConsentLog())
	if len(edges) != 1 {
		t.Fatalf("request-cookie path should yield 1 edge, got %d", len(edges))
	}
	if edges[0].SrcSite != "lemonde.fr" || edges[0].TrackerDomain != "doubleclick.net" {
		t.Errorf("edge = %q/%q want lemonde.fr/doubleclick.net", edges[0].SrcSite, edges[0].TrackerDomain)
	}
}

// TestConsentLog: loader fragment → pre_consent; CMP cookie → post_consent.
func TestConsentLog(t *testing.T) {
	cl := newConsentLog()
	if got := cl.stateFor("m", "lemonde.fr"); got != "none_seen" {
		t.Errorf("fresh → %q want none_seen", got)
	}
	// CMP loader request observed (no consent cookie yet) → pre_consent.
	cl.update("m", "lemonde.fr", "https://cdn.cookielaw.org/consent/scripttemplates/otSDKStub.js", nil)
	if got := cl.stateFor("m", "lemonde.fr"); got != "pre_consent" {
		t.Errorf("after CMP loader → %q want pre_consent", got)
	}
	// CMP consent cookie observed → post_consent.
	cl.update("m", "lemonde.fr", "https://www.lemonde.fr/", []string{"OptanonConsent=isGpcEnabled=0; Path=/"})
	if got := cl.stateFor("m", "lemonde.fr"); got != "post_consent" {
		t.Errorf("after CMP cookie → %q want post_consent", got)
	}
}

// TestSocialRelayFlush: the buffer batches edges and flushOnce POSTs them to the
// portal /__toolbox/social-event, then clears.
func TestSocialRelayFlush(t *testing.T) {
	var got socialEventPayload
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/__toolbox/social-event" {
			t.Errorf("unexpected path %q", r.URL.Path)
		}
		_ = json.NewDecoder(r.Body).Decode(&got)
		w.WriteHeader(204)
	}))
	defer srv.Close()

	s := newSocialRelay()
	s.add(socialEdge{ClientMacHash: "m", SrcSite: "a.fr", TrackerDomain: "t.com", CookieIDHashVal: "deadbeef", ConsentState: "none_seen"})
	p := s.flushOnce(srv.URL)
	if len(p.Edges) != 1 || len(got.Edges) != 1 {
		t.Fatalf("flush sent %d / server got %d, want 1/1", len(p.Edges), len(got.Edges))
	}
	if got.Edges[0].TrackerDomain != "t.com" {
		t.Errorf("server edge tracker = %q want t.com", got.Edges[0].TrackerDomain)
	}
	// Buffer cleared: a second flush sends nothing.
	if p2 := s.flushOnce(srv.URL); !p2.empty() {
		t.Errorf("second flush should be empty, got %d edges", len(p2.Edges))
	}
}

// TestSocialRelayCap: the buffer never exceeds socialBatchCap.
func TestSocialRelayCap(t *testing.T) {
	s := newSocialRelay()
	for i := 0; i < socialBatchCap+100; i++ {
		s.add(socialEdge{ClientMacHash: "m", SrcSite: "a", TrackerDomain: "t", CookieIDHashVal: "h", ConsentState: "none_seen"})
	}
	if got := s.snapshot(); len(got.Edges) != socialBatchCap {
		t.Errorf("buffer held %d edges, want cap %d", len(got.Edges), socialBatchCap)
	}
}
