# /etc/nginx/secubox.d/nettweak.conf
# Installed by secubox-nettweak package
location /api/v1/nettweak/ {
    proxy_pass http://unix:/run/secubox/nettweak.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}

location /nettweak/ {
    alias /usr/share/secubox/www/nettweak/;
    index index.html;
    try_files $uri $uri/ /nettweak/index.html;
}
