# /etc/nginx/secubox.d/avatar.conf
# Installed by secubox-avatar package
location /api/v1/avatar/ {
    proxy_pass http://unix:/run/secubox/avatar.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}

location /avatar/ {
    alias /usr/share/secubox/www/avatar/;
    index index.html;
    try_files $uri $uri/ /avatar/index.html;
}
