# /etc/nginx/secubox.d/cyberfeed.conf
# Installed by secubox-cyberfeed package
location /api/v1/cyberfeed/ {
    proxy_pass http://unix:/run/secubox/cyberfeed.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}
