# /etc/nginx/secubox.d/ipblock.conf
# SecuBox IPBlock API reverse proxy

location /api/v1/ipblock/ {
    proxy_pass http://unix:/run/secubox/ipblock.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}
