# /etc/nginx/secubox.d/vhost.conf
# Installed by secubox-vhost package
location /api/v1/vhost/ {
    proxy_pass http://unix:/run/secubox/vhost.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}
