# /etc/nginx/secubox.d/mqtt.conf
# Installed by secubox-mqtt package

# MQTT API
location /api/v1/mqtt/ {
    proxy_pass http://unix:/run/secubox/mqtt.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}

# MQTT Frontend
location /mqtt/ {
    alias /usr/share/secubox/www/mqtt/;
    index index.html;
    try_files $uri $uri/ /mqtt/index.html;
}
