# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Résout *.onion via Tor DNSPort (automap -> 10.192.0.0/10). private-domain
# empêche Unbound de stripper la réponse d'adresse privée (le range automap).
server:
    private-domain: "onion."
    do-not-query-localhost: no
forward-zone:
    name: "onion."
    forward-addr: 127.0.0.1@9053
