# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Résout *.onion via Tor DNSPort (automap -> 10.192.0.0/10). Trois choses :
#  - local-zone transparent : lève le blocage .onion par défaut d'Unbound
#    (RFC 6761 special-use => sinon NXDOMAIN autoritaire, jamais forwardé).
#  - domain-insecure : Tor DNSPort renvoie des réponses non signées (pas de DNSSEC).
#  - private-domain : n'écarte pas la réponse d'adresse privée (le range automap).
server:
    local-zone: "onion." transparent
    domain-insecure: "onion."
    private-domain: "onion."
    do-not-query-localhost: no
forward-zone:
    name: "onion."
    forward-addr: 127.0.0.1@9053
