# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Recreate /run/secubox at every boot (tmpfs is wiped on reboot).
# The helper service calls Path('/run/secubox').mkdir() at startup and
# crashes with PermissionError if the directory does not exist — see
# https://github.com/CyberMind-FR/secubox-deb/issues/133.
d /run/secubox      0755 secubox-eye-square secubox-eye-square -
d /var/log/secubox  0755 secubox-eye-square secubox-eye-square -
