# /etc/nginx/secubox.d/metablogizer.conf
# Installed by secubox-metablogizer package
location /api/v1/metablogizer/ {
    proxy_pass http://unix:/run/secubox/metablogizer.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}
