# board/espressobin-ultra/config.mk
# GlobalScale ESPRESSObin Ultra — Armada 3720, 2GB DDR4
# Ajouts : PoE WAN, M.2 SATA, Wi-Fi AC, LTE SIM slot

BOARD=espressobin-ultra
BOARD_SOC=armada-3720
ARCH=arm64
DEBIAN_ARCH=arm64
CROSS_COMPILE=aarch64-linux-gnu-

KERNEL_VERSION=6.6
KERNEL_DTS=armada-3720-espressobin-ultra
KERNEL_IMAGE=Image
KERNEL_DEFCONFIG=mvebu_v8_defconfig

KERNEL_EXTRAS=\
  CONFIG_MVNETA=y \
  CONFIG_NET_DSA=y \
  CONFIG_NET_DSA_MV88E6XXX=y \
  CONFIG_WIREGUARD=y \
  CONFIG_NF_TABLES=y \
  CONFIG_NFT_CT=y \
  CONFIG_NFT_NAT=y \
  CONFIG_NET_CLS_FLOWER=y \
  CONFIG_NET_ACT_MIRRED=y \
  CONFIG_IFB=y \
  CONFIG_NET_SCH_HTB=y \
  CONFIG_NET_SCH_INGRESS=y \
  CONFIG_RANDOMIZE_BASE=y \
  CONFIG_STACKPROTECTOR_STRONG=y \
  CONFIG_FORTIFY_SOURCE=y \
  CONFIG_SECURITY_APPARMOR=y \
  CONFIG_CFG80211=y \
  CONFIG_MAC80211=y

UBOOT_DEFCONFIG=mvebu_espressobin-88f3720_defconfig
ATF_PLATFORM=a3700

SECUBOX_PROFILE=secubox-lite
SECUBOX_LITE=1

WAN_IFACE=eth0
LAN_IFACES=lan0 lan1 lan2 lan3

DPI_MODE=passive
SWAP_SIZE=512M
