"""
SecuBox-Deb :: secubox-turn
CyberMind — https://cybermind.fr
Author: Gerald Kerma <gandalf@gk2.net>
License: Proprietary / ANSSI CSPN candidate

TURN/STUN server management for WebRTC using coturn.
"""
from fastapi import FastAPI, APIRouter, Depends, HTTPException
from pydantic import BaseModel
from secubox_core.auth import router as auth_router, require_jwt
from secubox_core.logger import get_logger
import subprocess
import json
import re
import hmac
import hashlib
import time
import secrets
from pathlib import Path
from typing import Optional, List

app = FastAPI(
    title="secubox-turn",
    version="1.0.0",
    root_path="/api/v1/turn"
)
app.include_router(auth_router, prefix="/auth")
router = APIRouter()
log = get_logger("turn")

# Paths
TURNSERVER_CONF = Path("/etc/turnserver.conf")
TURNADMIN_BIN = "/usr/bin/turnadmin"
USERS_DB = Path("/var/lib/secubox/turn/users.json")
CONFIG_CACHE = Path("/var/lib/secubox/turn/config_cache.json")

# Default coturn config template
DEFAULT_CONFIG = """# SecuBox TURN Server Configuration
# Generated by secubox-turn

# Network settings
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0

# Relay settings
relay-ip=AUTO_DETECT
min-port=49152
max-port=65535

# Authentication
lt-cred-mech
use-auth-secret
static-auth-secret=CHANGE_ME_SECRET

# Realm
realm=turn.secubox.local

# Logging
log-file=/var/log/turnserver/turnserver.log
verbose

# Security
no-multicast-peers
no-cli
fingerprint
"""


def _run_cmd(cmd: List[str], timeout: int = 30) -> dict:
    """Run a command and return result."""
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Command timed out"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def _service_status() -> dict:
    """Get coturn service status."""
    result = subprocess.run(
        ["systemctl", "is-active", "coturn"],
        capture_output=True,
        text=True
    )
    active = result.stdout.strip() == "active"

    enabled_result = subprocess.run(
        ["systemctl", "is-enabled", "coturn"],
        capture_output=True,
        text=True
    )
    enabled = enabled_result.stdout.strip() == "enabled"

    # Get process info if running
    pid = None
    uptime = None
    if active:
        pid_result = subprocess.run(
            ["pgrep", "-x", "turnserver"],
            capture_output=True,
            text=True
        )
        if pid_result.returncode == 0:
            pid = int(pid_result.stdout.strip().split()[0])
            # Get uptime from /proc
            try:
                stat = Path(f"/proc/{pid}/stat").read_text()
                starttime = int(stat.split()[21])
                uptime_sec = int(Path("/proc/uptime").read_text().split()[0])
                boot_time = time.time() - uptime_sec
                start_time = boot_time + (starttime / 100)
                uptime = int(time.time() - start_time)
            except Exception:
                pass

    return {
        "active": active,
        "enabled": enabled,
        "pid": pid,
        "uptime_seconds": uptime
    }


def _get_config() -> dict:
    """Parse turnserver.conf into dict."""
    config = {}
    if TURNSERVER_CONF.exists():
        for line in TURNSERVER_CONF.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, value = line.split("=", 1)
                config[key.strip()] = value.strip()
            else:
                config[line] = True
    return config


def _get_users() -> List[dict]:
    """Get TURN users from users.json."""
    if USERS_DB.exists():
        try:
            return json.loads(USERS_DB.read_text())
        except Exception:
            pass
    return []


def _save_users(users: List[dict]):
    """Save TURN users to users.json."""
    USERS_DB.parent.mkdir(parents=True, exist_ok=True)
    USERS_DB.write_text(json.dumps(users, indent=2))


def _get_realm() -> str:
    """Get current realm from config."""
    config = _get_config()
    return config.get("realm", "turn.secubox.local")


def _get_secret() -> str:
    """Get static auth secret from config."""
    config = _get_config()
    return config.get("static-auth-secret", "")


def _generate_temp_credentials(username: str, ttl: int = 86400) -> dict:
    """Generate temporary TURN credentials using HMAC."""
    secret = _get_secret()
    if not secret:
        return {"error": "No static-auth-secret configured"}

    timestamp = int(time.time()) + ttl
    temp_username = f"{timestamp}:{username}"

    # HMAC-SHA1 password
    password = hmac.new(
        secret.encode(),
        temp_username.encode(),
        hashlib.sha1
    ).digest()

    import base64
    password_b64 = base64.b64encode(password).decode()

    realm = _get_realm()
    config = _get_config()
    port = config.get("listening-port", "3478")
    tls_port = config.get("tls-listening-port", "5349")

    return {
        "username": temp_username,
        "password": password_b64,
        "ttl": ttl,
        "expires": timestamp,
        "realm": realm,
        "turn_urls": [
            f"turn:{realm}:{port}",
            f"turn:{realm}:{port}?transport=tcp",
            f"turns:{realm}:{tls_port}",
        ],
        "stun_urls": [
            f"stun:{realm}:{port}",
        ]
    }


def _parse_sessions_from_cli() -> List[dict]:
    """Parse active sessions from turnserver CLI or logs."""
    sessions = []

    # Try to get sessions from CLI if enabled
    result = subprocess.run(
        ["ss", "-tunp"],
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        for line in result.stdout.splitlines():
            if "turnserver" in line:
                parts = line.split()
                if len(parts) >= 5:
                    # Parse local and remote addresses
                    local = parts[4] if len(parts) > 4 else "-"
                    remote = parts[5] if len(parts) > 5 else "-"
                    sessions.append({
                        "protocol": parts[0],
                        "local_addr": local,
                        "remote_addr": remote,
                        "state": parts[1] if len(parts) > 1 else "UNKNOWN"
                    })

    return sessions


def _get_stats_from_logs() -> dict:
    """Parse statistics from turnserver logs."""
    stats = {
        "total_allocations": 0,
        "active_allocations": 0,
        "total_data_relayed": 0,
        "auth_failures": 0
    }

    log_file = Path("/var/log/turnserver/turnserver.log")
    if log_file.exists():
        try:
            # Read last 1000 lines
            lines = log_file.read_text().splitlines()[-1000:]
            for line in lines:
                if "allocation created" in line.lower():
                    stats["total_allocations"] += 1
                if "allocation deleted" in line.lower():
                    stats["active_allocations"] = max(0, stats["total_allocations"] - 1)
                if "authentication failed" in line.lower():
                    stats["auth_failures"] += 1
        except Exception:
            pass

    return stats


# ══════════════════════════════════════════════════════════════════════════════
# API Endpoints
# ══════════════════════════════════════════════════════════════════════════════

@router.get("/health")
async def health():
    """Health check endpoint (public)."""
    return {"status": "ok", "module": "turn", "version": "1.0.0"}


@router.get("/status")
async def status(user=Depends(require_jwt)):
    """Get TURN server status."""
    svc = _service_status()
    config = _get_config()

    return {
        "service": svc,
        "realm": config.get("realm", ""),
        "listening_port": config.get("listening-port", "3478"),
        "tls_port": config.get("tls-listening-port", "5349"),
        "min_port": config.get("min-port", "49152"),
        "max_port": config.get("max-port", "65535"),
        "config_exists": TURNSERVER_CONF.exists(),
        "users_count": len(_get_users())
    }


@router.get("/stats")
async def stats(user=Depends(require_jwt)):
    """Get connection statistics."""
    sessions = _parse_sessions_from_cli()
    log_stats = _get_stats_from_logs()

    # Count connections by type
    udp_count = sum(1 for s in sessions if s.get("protocol", "").startswith("udp"))
    tcp_count = sum(1 for s in sessions if s.get("protocol", "").startswith("tcp"))

    return {
        "active_sessions": len(sessions),
        "udp_connections": udp_count,
        "tcp_connections": tcp_count,
        "total_allocations": log_stats["total_allocations"],
        "auth_failures": log_stats["auth_failures"],
        "total_data_relayed_bytes": log_stats["total_data_relayed"]
    }


@router.get("/sessions")
async def sessions(user=Depends(require_jwt)):
    """Get active sessions with client IPs."""
    sessions = _parse_sessions_from_cli()

    # Enrich with client info
    enriched = []
    for s in sessions:
        remote = s.get("remote_addr", "")
        if ":" in remote:
            parts = remote.rsplit(":", 1)
            client_ip = parts[0]
            client_port = parts[1] if len(parts) > 1 else ""
        else:
            client_ip = remote
            client_port = ""

        enriched.append({
            "client_ip": client_ip,
            "client_port": client_port,
            "protocol": s.get("protocol", ""),
            "local_addr": s.get("local_addr", ""),
            "state": s.get("state", "")
        })

    return {"sessions": enriched, "count": len(enriched)}


@router.post("/start")
async def start(user=Depends(require_jwt)):
    """Start coturn service."""
    result = _run_cmd(["systemctl", "start", "coturn"])
    log.info("TURN start requested: %s", result.get("success"))
    return result


@router.post("/stop")
async def stop(user=Depends(require_jwt)):
    """Stop coturn service."""
    result = _run_cmd(["systemctl", "stop", "coturn"])
    log.info("TURN stop requested: %s", result.get("success"))
    return result


@router.post("/restart")
async def restart(user=Depends(require_jwt)):
    """Restart coturn service."""
    result = _run_cmd(["systemctl", "restart", "coturn"])
    log.info("TURN restart requested: %s", result.get("success"))
    return result


@router.get("/config")
async def get_config(user=Depends(require_jwt)):
    """Get turnserver.conf configuration."""
    if TURNSERVER_CONF.exists():
        return {
            "content": TURNSERVER_CONF.read_text(),
            "parsed": _get_config()
        }
    return {"content": "", "parsed": {}, "error": "Config file not found"}


class ConfigRequest(BaseModel):
    content: str


@router.post("/config")
async def set_config(req: ConfigRequest, user=Depends(require_jwt)):
    """Update turnserver.conf configuration."""
    try:
        # Backup current config
        if TURNSERVER_CONF.exists():
            backup = TURNSERVER_CONF.with_suffix(".conf.bak")
            backup.write_text(TURNSERVER_CONF.read_text())

        # Write new config
        TURNSERVER_CONF.write_text(req.content)
        log.info("TURN config updated")

        return {"success": True, "message": "Config updated. Restart service to apply."}
    except Exception as e:
        log.error("Config update failed: %s", e)
        return {"success": False, "error": str(e)}


@router.get("/users")
async def list_users(user=Depends(require_jwt)):
    """List TURN users."""
    users = _get_users()
    # Don't expose passwords
    return {
        "users": [
            {"username": u.get("username"), "created": u.get("created")}
            for u in users
        ]
    }


class UserRequest(BaseModel):
    username: str
    password: str


@router.post("/users")
async def add_user(req: UserRequest, user=Depends(require_jwt)):
    """Add a TURN user."""
    users = _get_users()

    # Check if user exists
    for u in users:
        if u.get("username") == req.username:
            return {"success": False, "error": "User already exists"}

    # Add user
    users.append({
        "username": req.username,
        "password": req.password,
        "created": int(time.time())
    })
    _save_users(users)

    # Also add to turnadmin if available
    realm = _get_realm()
    if Path(TURNADMIN_BIN).exists():
        _run_cmd([
            TURNADMIN_BIN, "-a", "-u", req.username,
            "-p", req.password, "-r", realm
        ])

    log.info("TURN user added: %s", req.username)
    return {"success": True, "message": f"User {req.username} added"}


@router.delete("/users/{username}")
async def delete_user(username: str, user=Depends(require_jwt)):
    """Delete a TURN user."""
    users = _get_users()
    new_users = [u for u in users if u.get("username") != username]

    if len(new_users) == len(users):
        return {"success": False, "error": "User not found"}

    _save_users(new_users)

    # Also remove from turnadmin if available
    realm = _get_realm()
    if Path(TURNADMIN_BIN).exists():
        _run_cmd([
            TURNADMIN_BIN, "-d", "-u", username, "-r", realm
        ])

    log.info("TURN user deleted: %s", username)
    return {"success": True, "message": f"User {username} deleted"}


@router.get("/realm")
async def get_realm_endpoint(user=Depends(require_jwt)):
    """Get realm configuration."""
    return {
        "realm": _get_realm(),
        "secret_configured": bool(_get_secret())
    }


class RealmRequest(BaseModel):
    realm: str
    secret: Optional[str] = None


@router.post("/realm")
async def set_realm(req: RealmRequest, user=Depends(require_jwt)):
    """Set realm and optionally regenerate secret."""
    if not TURNSERVER_CONF.exists():
        return {"success": False, "error": "Config file not found"}

    content = TURNSERVER_CONF.read_text()

    # Update realm
    if "realm=" in content:
        content = re.sub(r"realm=.*", f"realm={req.realm}", content)
    else:
        content += f"\nrealm={req.realm}\n"

    # Update secret if provided
    if req.secret:
        if "static-auth-secret=" in content:
            content = re.sub(r"static-auth-secret=.*", f"static-auth-secret={req.secret}", content)
        else:
            content += f"\nstatic-auth-secret={req.secret}\n"

    TURNSERVER_CONF.write_text(content)
    log.info("TURN realm updated: %s", req.realm)

    return {
        "success": True,
        "realm": req.realm,
        "message": "Restart service to apply changes"
    }


class CredentialRequest(BaseModel):
    username: str = "webrtc"
    ttl: int = 86400


@router.get("/credentials")
async def get_credentials(user=Depends(require_jwt)):
    """Generate temporary TURN credentials for testing."""
    return _generate_temp_credentials("test-user", 3600)


@router.post("/credentials")
async def generate_credentials(req: CredentialRequest, user=Depends(require_jwt)):
    """Generate temporary TURN credentials with custom username and TTL."""
    return _generate_temp_credentials(req.username, req.ttl)


@router.post("/generate_secret")
async def generate_secret(user=Depends(require_jwt)):
    """Generate a new random auth secret."""
    new_secret = secrets.token_hex(32)
    return {"secret": new_secret}


@router.get("/logs")
async def get_logs(lines: int = 100, user=Depends(require_jwt)):
    """Get TURN server logs."""
    log_file = Path("/var/log/turnserver/turnserver.log")

    if log_file.exists():
        try:
            all_lines = log_file.read_text().splitlines()
            return {"lines": all_lines[-lines:]}
        except Exception as e:
            return {"lines": [], "error": str(e)}

    # Try journalctl as fallback
    result = subprocess.run(
        ["journalctl", "-u", "coturn", "-n", str(lines), "--no-pager"],
        capture_output=True,
        text=True,
        timeout=10
    )
    return {"lines": result.stdout.splitlines()}


# Three-fold architecture endpoints

@router.get("/components")
async def components(user=Depends(require_jwt)):
    """List TURN server components (Three-fold architecture)."""
    return {
        "components": [
            {
                "name": "coturn",
                "type": "service",
                "description": "TURN/STUN server daemon",
                "status": _service_status()["active"]
            },
            {
                "name": "turnadmin",
                "type": "cli",
                "description": "User management CLI",
                "available": Path(TURNADMIN_BIN).exists()
            },
            {
                "name": "turnserver.conf",
                "type": "config",
                "description": "Main configuration file",
                "exists": TURNSERVER_CONF.exists()
            }
        ]
    }


@router.get("/access")
async def access(user=Depends(require_jwt)):
    """Get access endpoints (Three-fold architecture)."""
    config = _get_config()
    realm = config.get("realm", "localhost")
    port = config.get("listening-port", "3478")
    tls_port = config.get("tls-listening-port", "5349")

    return {
        "endpoints": [
            {
                "name": "STUN UDP",
                "protocol": "stun",
                "host": realm,
                "port": int(port),
                "url": f"stun:{realm}:{port}"
            },
            {
                "name": "TURN UDP",
                "protocol": "turn",
                "host": realm,
                "port": int(port),
                "url": f"turn:{realm}:{port}"
            },
            {
                "name": "TURN TCP",
                "protocol": "turn",
                "host": realm,
                "port": int(port),
                "url": f"turn:{realm}:{port}?transport=tcp"
            },
            {
                "name": "TURNS TLS",
                "protocol": "turns",
                "host": realm,
                "port": int(tls_port),
                "url": f"turns:{realm}:{tls_port}"
            }
        ]
    }


app.include_router(router)
