#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# SecuBox-Deb :: secubox-mqtt :: install-lxc.sh
#
# Idempotent LXC bootstrap for Mosquitto 2.x. Safe to re-run.
# Inherits all 11 install-lxc fixes from v2.11.1 + Authelia v1.0.1 + Lyrion v1.0.3.
#
# Hard limits enforced (per docs/superpowers/specs/2026-05-20-secubox-zigbee-mqtt-iot-stack.md):
#   - allow_anonymous false (never true)
#   - acl_file: per-service topic ACL
#   - User systemd: mosquitto user, NoNewPrivileges baked into upstream unit
#   - Listener bound to 0.0.0.0 inside the LXC, exposed to LAN via DNAT (port 1883)
# Follows docs/MODULE-GUIDELINES.md §3 + §7.

set -euo pipefail

readonly LXC_NAME="${SECUBOX_LXC_NAME:-mqtt}"
readonly LXC_IP="${SECUBOX_LXC_IP:-10.100.0.110}"
readonly LXC_PATH="${SECUBOX_LXC_PATH:-/data/lxc}"
readonly LXC_BRIDGE="${SECUBOX_LXC_BRIDGE:-br-lxc}"
readonly LXC_GW="${SECUBOX_LXC_GW:-10.100.0.1}"
readonly DEBIAN_SUITE="${SECUBOX_DEBIAN_SUITE:-bookworm}"
readonly MQTT_PORT="${SECUBOX_MQTT_PORT:-1883}"
readonly STATE_DIR="${SECUBOX_STATE_DIR:-/var/lib/secubox/mqtt}"
readonly SECRETS_DIR="${SECUBOX_SECRETS_DIR:-/etc/secubox/secrets}"
readonly SENTINEL="$STATE_DIR/.lxc-provisioned"
# ACL services — keep in sync with sbin/mqttctl access-list.
# Format: "user:topic-glob"
readonly ACL_SERVICES=(
    "z2m:zigbee2mqtt/#"
    "sentinelle:sentinelle/#"
    "domoticz:domoticz/#"
    "homeassistant:homeassistant/#"
    "secubox-api:#"
)

log()  { printf '[mqtt-install] %s\n' "$*"; }
fail() { printf '[mqtt-install] ERROR: %s\n' "$*" >&2; exit 1; }

require_cmds() {
    for c in lxc-create lxc-info lxc-start lxc-attach openssl nft; do
        command -v "$c" >/dev/null 2>&1 || fail "$c not installed"
    done
}

ensure_dirs() {
    install -d -m 0755 -o root -g root "$LXC_PATH"
    install -d -m 0755 -o secubox -g secubox "$STATE_DIR"
    install -d -m 0700 -o root -g root "$SECRETS_DIR"
}

ensure_bridge() {
    if ! ip link show "$LXC_BRIDGE" >/dev/null 2>&1; then
        log "Creating bridge $LXC_BRIDGE @ ${LXC_GW}/24 ..."
        ip link add name "$LXC_BRIDGE" type bridge
        ip addr add "${LXC_GW}/24" dev "$LXC_BRIDGE"
        ip link set "$LXC_BRIDGE" up
    fi
}

ensure_masquerade() {
    if ! nft list table ip lxc 2>/dev/null | grep -q 'saddr 10.100.0.0/24'; then
        log "Adding nftables MASQUERADE for 10.100.0.0/24 ..."
        nft 'add table ip lxc' 2>/dev/null || true
        nft 'add chain ip lxc postrouting { type nat hook postrouting priority srcnat ; policy accept ; }' 2>/dev/null || true
        nft 'add rule ip lxc postrouting ip saddr 10.100.0.0/24 ip daddr != 10.100.0.0/24 counter masquerade' 2>/dev/null || true
    fi
}

# DNAT broker port from the LAN to the LXC. Mosquitto in the LXC binds
# 0.0.0.0:1883 but the bridge is not reachable from the LAN. Same pattern
# as secubox-lyrion :3483 (slimproto). Persistent file in /etc/nftables.d/.
ensure_broker_dnat() {
    local nft_file="/etc/nftables.d/secubox-mqtt-dnat.nft"
    local lan_iface="${SECUBOX_LAN_IFACE:-lan0}"
    log "Ensuring broker DNAT ${lan_iface}:${MQTT_PORT} → ${LXC_IP}:${MQTT_PORT} ..."
    install -d -m 0755 /etc/nftables.d
    cat > "$nft_file" <<NFT
# /etc/nftables.d/secubox-mqtt-dnat.nft
# DNAT MQTT broker (TCP :${MQTT_PORT}) from LAN to the Mosquitto LXC.
# Lets LAN clients (z2m, sentinelle, domoticz, homeassistant) reach the
# broker without bridging the LXC network into the LAN.
# Generated by secubox-mqtt install-lxc.sh (#240).

table inet secubox-mqtt {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        iifname "${lan_iface}" tcp dport ${MQTT_PORT} dnat ip to ${LXC_IP}:${MQTT_PORT} comment "mqtt-broker"
    }
}
NFT
    chmod 0644 "$nft_file"
    nft 'delete table inet secubox-mqtt' 2>/dev/null || true
    nft -f "$nft_file" 2>&1
}

lxc_state() {
    lxc-info -n "$LXC_NAME" -P "$LXC_PATH" 2>/dev/null \
        | awk -F: '/^State:/ { gsub(/ /,"",$2); print tolower($2) }'
}

create_lxc() {
    if [ -d "$LXC_PATH/$LXC_NAME/rootfs" ]; then
        log "LXC '$LXC_NAME' already exists — skipping debootstrap"
        return
    fi
    log "Creating LXC '$LXC_NAME' (debian $DEBIAN_SUITE) ..."
    lxc-create -n "$LXC_NAME" -t download -P "$LXC_PATH" \
        -- --dist debian --release "$DEBIAN_SUITE" \
           --arch "$(dpkg --print-architecture)"
}

write_lxc_config() {
    log "Pinning network: $LXC_IP/24 on $LXC_BRIDGE"
    cat > "$LXC_PATH/$LXC_NAME/config" <<EOF
# SecuBox-managed — see secubox-mqtt / install-lxc.sh
lxc.uts.name = $LXC_NAME
lxc.net.0.type = veth
lxc.net.0.link = $LXC_BRIDGE
lxc.net.0.flags = up
lxc.net.0.ipv4.address = $LXC_IP/24
lxc.net.0.ipv4.gateway = $LXC_GW
lxc.net.0.name = eth0
lxc.rootfs.path = dir:$LXC_PATH/$LXC_NAME/rootfs
lxc.include = /usr/share/lxc/config/common.conf
lxc.apparmor.profile = generated
lxc.start.auto = 1
lxc.start.delay = 5
EOF
}

start_lxc() {
    [ "$(lxc_state)" = "running" ] && { log "Already running"; return; }
    log "Starting LXC '$LXC_NAME' ..."
    lxc-start -n "$LXC_NAME" -P "$LXC_PATH"
}

wait_for_network() {
    log "Waiting for LXC network ..."
    for _ in $(seq 1 30); do
        lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- ping -c1 -W1 "$LXC_GW" >/dev/null 2>&1 && return 0
        sleep 1
    done
    fail "LXC '$LXC_NAME' did not reach $LXC_GW within 30s"
}

ensure_resolv() {
    log "Seeding /etc/resolv.conf in LXC ..."
    lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- sh -c '
        rm -f /etc/resolv.conf
        printf "nameserver 1.1.1.1\nnameserver 9.9.9.9\n" > /etc/resolv.conf
    '
}

# ── Mosquitto install inside LXC ────────────────────────────────────────────
# Debian ships mosquitto 2.0.x in bookworm (`mosquitto`, `mosquitto-clients`).
# That's recent enough — no need for an external apt repo.
install_mosquitto_in_lxc() {
    log "Installing Mosquitto in '$LXC_NAME' ..."
    lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- bash -e <<'INNER'
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -q
        apt-get install -y --no-install-recommends \
            ca-certificates mosquitto mosquitto-clients

        # The Debian package ships /etc/mosquitto/mosquitto.conf with an
        # `include_dir /etc/mosquitto/conf.d` directive — we drop our own
        # conf.d snippet rather than rewriting mosquitto.conf.
        systemctl daemon-reload
        systemctl enable mosquitto
INNER
}

# Generate a strong random password for each ACL service. Stored on the host
# under /etc/secubox/secrets/mqtt-<service> (mode 0600), then loaded into
# the LXC via lxc-attach + mosquitto_passwd. Idempotent: only writes a new
# password if the file doesn't exist (so re-running the install never
# rotates working credentials).
generate_passwords() {
    install -d -m 0750 -o root -g secubox "$SECRETS_DIR"
    for entry in "${ACL_SERVICES[@]}"; do
        local user="${entry%%:*}"
        local file="$SECRETS_DIR/mqtt-${user}"
        if [ ! -f "$file" ]; then
            local pw; pw=$(openssl rand -hex 16)
            printf '%s\n' "$pw" > "$file"
            chmod 0640 "$file"
            chown root:secubox "$file"
            log "  · generated mqtt-${user} (32 hex chars)"
        fi
    done
}

# Render mosquitto config + ACL + passwd inside the LXC. Always overwrites
# the SecuBox-managed files — operator edits should go in a sibling
# conf.d snippet, not in /etc/mosquitto/conf.d/secubox.conf.
configure_mosquitto() {
    log "Rendering mosquitto config + ACL + passwd ..."

    # Build the passwd file host-side using mosquitto_passwd's deterministic
    # hash (PBKDF2-SHA512). Stage it on the host then ship into the LXC.
    local stage_passwd=/tmp/secubox-mqtt-passwd.$$
    local stage_acl=/tmp/secubox-mqtt-acl.$$
    : > "$stage_passwd"
    : > "$stage_acl"
    for entry in "${ACL_SERVICES[@]}"; do
        local user="${entry%%:*}"
        local topic="${entry#*:}"
        local pw_file="$SECRETS_DIR/mqtt-${user}"
        [ -f "$pw_file" ] || fail "missing $pw_file (generate_passwords should have created it)"
        local pw; pw=$(cat "$pw_file")
        # Append user:plain to a staging file; mosquitto_passwd -U hashes in place.
        printf '%s:%s\n' "$user" "$pw" >> "$stage_passwd"
        printf 'user %s\ntopic readwrite %s\n\n' "$user" "$topic" >> "$stage_acl"
    done

    # Mosquitto config snippet — listener, ACL, passwd, persistence.
    local stage_conf=/tmp/secubox-mqtt-conf.$$
    cat > "$stage_conf" <<CONF
# /etc/mosquitto/conf.d/secubox.conf
# Generated by secubox-mqtt install-lxc.sh — do not edit by hand.
# Operator overrides should go in a sibling conf.d snippet (which loads after).
#
# NOTE: keys with single-value semantics in mosquitto 2.x (persistence,
# persistence_location, log_dest, pid_file) are ALREADY set by Debian's
# default /etc/mosquitto/mosquitto.conf, and mosquitto 2.x rejects
# duplicates with "Error: Duplicate ... value in configuration."
# We only set what the default leaves unset: listener, ACL, passwd,
# anonymous policy, log levels (log_type is additive — multiple OK).
listener ${MQTT_PORT} 0.0.0.0
allow_anonymous false
password_file /etc/mosquitto/passwd.d/secubox
acl_file /etc/mosquitto/acl.d/secubox.acl
log_type error
log_type warning
log_type notice
max_queued_messages 1000
CONF

    # Ship into the LXC.
    lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- install -d -m 0750 -o mosquitto -g mosquitto /etc/mosquitto/passwd.d /etc/mosquitto/acl.d
    cat "$stage_passwd" | lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- tee /etc/mosquitto/passwd.d/secubox.plain >/dev/null
    cat "$stage_acl"    | lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- tee /etc/mosquitto/acl.d/secubox.acl     >/dev/null
    cat "$stage_conf"   | lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- tee /etc/mosquitto/conf.d/secubox.conf   >/dev/null

    # Hash the staged plain passwd file in place (-U). Then move to the final
    # path mosquitto actually reads, removing the .plain leftover.
    lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- bash -e <<'INNER'
        set -euo pipefail
        cp /etc/mosquitto/passwd.d/secubox.plain /etc/mosquitto/passwd.d/secubox
        mosquitto_passwd -U /etc/mosquitto/passwd.d/secubox
        rm -f /etc/mosquitto/passwd.d/secubox.plain
        chown mosquitto:mosquitto /etc/mosquitto/passwd.d/secubox /etc/mosquitto/acl.d/secubox.acl /etc/mosquitto/conf.d/secubox.conf
        chmod 0640 /etc/mosquitto/passwd.d/secubox /etc/mosquitto/acl.d/secubox.acl
        chmod 0644 /etc/mosquitto/conf.d/secubox.conf
INNER

    # Write a host-side cached copy of the ACL so the unprivileged FastAPI
    # (running as `secubox`, no lxc-attach perms) can serve /api/v1/mqtt/access.
    cp "$stage_acl" /etc/secubox/mqtt-acl.cached
    chmod 0640 /etc/secubox/mqtt-acl.cached
    chown root:secubox /etc/secubox/mqtt-acl.cached

    rm -f "$stage_passwd" "$stage_acl" "$stage_conf"

    lxc-attach -n "$LXC_NAME" -P "$LXC_PATH" -- systemctl restart mosquitto
}

mark_provisioned() {
    install -d -m 0755 -o secubox -g secubox "$STATE_DIR"
    date -Iseconds > "$SENTINEL"
}

# v2.4.0 moves Mosquitto into an LXC; the v1.0.0 host-bound install left
# a separate mosquitto running on the host (bound to 127.0.0.1:1883 by
# default). It doesn't steal the LAN port — DNAT bypasses it — but it
# wastes RAM, may persist stale state, and confuses ss/netstat output.
# Stop + disable + mask it on every install (idempotent — masking a
# masked unit is a noop, stopping a stopped unit is a noop).
migrate_from_v1() {
    # is-active returns 0 only if active; we don't need list-unit-files —
    # is-active is already a sufficient existence check.
    if systemctl is-active --quiet mosquitto 2>/dev/null; then
        log "Stopping host-side mosquitto (v1.0.0 leftover) ..."
        systemctl stop mosquitto    2>/dev/null || true
        systemctl disable mosquitto 2>/dev/null || true
        systemctl mask mosquitto    2>/dev/null || true
    fi
}

main() {
    require_cmds
    migrate_from_v1
    ensure_dirs
    ensure_bridge
    ensure_masquerade
    create_lxc
    write_lxc_config
    start_lxc
    wait_for_network
    ensure_resolv
    install_mosquitto_in_lxc
    generate_passwords
    configure_mosquitto
    ensure_broker_dnat
    mark_provisioned
    log "OK — LXC '$LXC_NAME' at $LXC_IP, Mosquitto provisioned + running."
    log "  · Broker (LXC) : tcp://$LXC_IP:$MQTT_PORT/"
    log "  · Broker (LAN) : tcp://<board-ip>:$MQTT_PORT/  (DNAT'd)"
    log "  · ACL services : ${ACL_SERVICES[*]}"
    log "  · Secrets      : $SECRETS_DIR/mqtt-{z2m,sentinelle,domoticz,homeassistant,secubox-api}"
}

main "$@"
