# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# SecuBox-Deb :: nDPId socket dir. Parent /run/secubox stays 1777 root:root
# (shared by ~95 units — never a RuntimeDirectory). The ndpi subdir is owned by
# the engine user so nDPIsrvd can create its collector/distributor sockets and
# sbxdpi (same user) can dial the distributor.
d /run/secubox 1777 root root - -
d /run/secubox/ndpi 0755 secubox-toolbox secubox-toolbox - -
