# /etc/nginx/secubox.d/smtp-relay.conf
# Installed by secubox-smtp-relay package
location /api/v1/smtp-relay/ {
    proxy_pass http://unix:/run/secubox/smtp-relay.sock:/;
    include /etc/nginx/snippets/secubox-proxy.conf;
}

location /smtp-relay/ {
    alias /usr/share/secubox/www/smtp-relay/;
    index index.html;
    try_files $uri $uri/ /smtp-relay/index.html;
}
