# SPDX-License-Identifier: LicenseRef-CMSD-1.0
# Dossier d'état réservé au compte du service : l'historique de navigation par appareil n'est lisible par aucun autre module (groupe secubox exclu).
d /var/lib/secubox/webfilter 0700 secubox-webfilter secubox-webfilter -
d /var/lib/secubox/webfilter/listes 0700 secubox-webfilter secubox-webfilter -
